/**
 * Picklist registry.
 *
 * Transcribed from "Nucleus_Forms_and_Fields_Complete_MKraft.xlsx", sheet 03_Picklists,
 * which is the source of truth for every dropdown vocabulary in the product. Each entry
 * carries the workbook's own declared value count, and `picklists.test.ts` asserts the
 * transcription still matches it, so a value cannot be dropped or invented unnoticed.
 *
 * `seededBy` repeats the workbook column: "config" = tenant-editable, "system" = fixed.
 * `openSet` names a value set the workbook defers to an external standard seeded at
 * install. Those are NOT enumerated here - only the value the workbook itself states is
 * listed, and the seed source is recorded so the rest is loaded rather than guessed.
 *
 * Stored values are the slugs below (lower snake case); `label` is what the workbook prints.
 */

export type PicklistEntry = { readonly value: string; readonly label: string };
export type Picklist = {
  readonly code: string;
  readonly name: string;
  readonly seededBy: "config" | "system";
  /** The value count the workbook declares for this picklist. */
  readonly declared: number;
  /** Set when the workbook defers the full set to an external standard. */
  readonly openSet: string | null;
  readonly values: readonly PicklistEntry[];
};

export const picklists = {
  PL_ACCOMMODATION: {
    code: "PL_ACCOMMODATION",
    name: "Accommodation type",
    seededBy: "config",
    declared: 5,
    openSet: null,
    values: [
      { value: "own", label: "Own" },
      { value: "rented", label: "Rented" },
      { value: "company_provided", label: "Company provided" },
      { value: "parental", label: "Parental" },
      { value: "hostel", label: "Hostel" },
    ],
  },
  PL_ACCOUNT_TYPE: {
    code: "PL_ACCOUNT_TYPE",
    name: "Bank account type",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "savings", label: "Savings" },
      { value: "current", label: "Current" },
      { value: "salary", label: "Salary" },
      { value: "nre", label: "NRE" },
      { value: "nro", label: "NRO" },
    ],
  },
  PL_ACCRUAL_DAY: {
    code: "PL_ACCRUAL_DAY",
    name: "Accrual timing",
    seededBy: "config",
    declared: 2,
    openSet: null,
    values: [
      { value: "period_start", label: "Period start" },
      { value: "period_end", label: "Period end" },
    ],
  },
  PL_ACCRUAL_METHOD: {
    code: "PL_ACCRUAL_METHOD",
    name: "Accrual method",
    seededBy: "config",
    declared: 4,
    openSet: null,
    values: [
      { value: "annual_credit", label: "Annual credit" },
      { value: "monthly_accrual", label: "Monthly accrual" },
      { value: "per_days_worked", label: "Per days worked" },
      { value: "no_accrual_entitlement_based", label: "No accrual (entitlement based)" },
    ],
  },
  PL_ACTIVE_STATUS: {
    code: "PL_ACTIVE_STATUS",
    name: "Record status",
    seededBy: "system",
    declared: 2,
    openSet: null,
    values: [
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
    ],
  },
  PL_ANNOUNCEMENT_CHANNEL: {
    code: "PL_ANNOUNCEMENT_CHANNEL",
    name: "Announcement channel",
    seededBy: "config",
    declared: 5,
    openSet: null,
    values: [
      { value: "employee_portal", label: "Employee portal" },
      { value: "mobile_push", label: "Mobile push" },
      { value: "email", label: "Email" },
      { value: "whatsapp", label: "WhatsApp" },
      { value: "notice_board_display", label: "Notice board display" },
    ],
  },
  PL_ANNOUNCEMENT_TYPE: {
    code: "PL_ANNOUNCEMENT_TYPE",
    name: "Announcement type",
    seededBy: "config",
    declared: 5,
    openSet: null,
    values: [
      { value: "general", label: "General" },
      { value: "policy", label: "Policy" },
      { value: "emergency", label: "Emergency" },
      { value: "celebration", label: "Celebration" },
      { value: "statutory_notice", label: "Statutory notice" },
    ],
  },
  PL_APPROVAL_STATUS: {
    code: "PL_APPROVAL_STATUS",
    name: "Approval status",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "draft", label: "Draft" },
      { value: "pending_approval", label: "Pending approval" },
      { value: "approved", label: "Approved" },
      { value: "rejected", label: "Rejected" },
      { value: "withdrawn", label: "Withdrawn" },
    ],
  },
  PL_ASSET_CONDITION: {
    code: "PL_ASSET_CONDITION",
    name: "Asset condition at issue",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "new", label: "New" },
      { value: "good", label: "Good" },
      { value: "fair", label: "Fair" },
    ],
  },
  PL_ASSET_RETURN_CONDITION: {
    code: "PL_ASSET_RETURN_CONDITION",
    name: "Asset condition at return",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "good", label: "Good" },
      { value: "damaged", label: "Damaged" },
      { value: "lost", label: "Lost" },
      { value: "not_returned", label: "Not returned" },
    ],
  },
  PL_ASSET_TYPE: {
    code: "PL_ASSET_TYPE",
    name: "Asset type",
    seededBy: "config",
    declared: 12,
    openSet: null,
    values: [
      { value: "laptop", label: "Laptop" },
      { value: "desktop", label: "Desktop" },
      { value: "mobile_phone", label: "Mobile phone" },
      { value: "sim_card", label: "SIM card" },
      { value: "access_card", label: "Access card" },
      { value: "vehicle", label: "Vehicle" },
      { value: "tool_kit", label: "Tool kit" },
      { value: "safety_equipment", label: "Safety equipment" },
      { value: "uniform", label: "Uniform" },
      { value: "footwear", label: "Footwear" },
      { value: "locker_key", label: "Locker key" },
      { value: "other", label: "Other" },
    ],
  },
  PL_ASSIGNMENT_CHANGE: {
    code: "PL_ASSIGNMENT_CHANGE",
    name: "Assignment change type",
    seededBy: "config",
    declared: 10,
    openSet: null,
    values: [
      { value: "new_hire", label: "New hire" },
      { value: "promotion", label: "Promotion" },
      { value: "transfer_location", label: "Transfer — location" },
      { value: "transfer_org_unit", label: "Transfer — org unit" },
      { value: "redesignation", label: "Redesignation" },
      { value: "worker_class_change", label: "Worker class change" },
      { value: "manager_change", label: "Manager change" },
      { value: "payroll_group_change", label: "Payroll group change" },
      { value: "data_correction", label: "Data correction" },
      { value: "rehire", label: "Rehire" },
    ],
  },
  PL_ATTENDANCE_MODE: {
    code: "PL_ATTENDANCE_MODE",
    name: "Attendance capture mode",
    seededBy: "config",
    declared: 6,
    openSet: null,
    values: [
      { value: "biometric_device", label: "Biometric device" },
      { value: "mobile_app", label: "Mobile app" },
      { value: "kiosk", label: "Kiosk" },
      { value: "whatsapp", label: "WhatsApp" },
      { value: "web", label: "Web" },
      { value: "exempt", label: "Exempt" },
    ],
  },
  PL_ATTENDANCE_STATUS: {
    code: "PL_ATTENDANCE_STATUS",
    name: "Attendance day status",
    seededBy: "system",
    declared: 9,
    openSet: null,
    values: [
      { value: "present", label: "Present" },
      { value: "half_day", label: "Half day" },
      { value: "absent", label: "Absent" },
      { value: "weekly_off", label: "Weekly off" },
      { value: "holiday", label: "Holiday" },
      { value: "on_leave", label: "On leave" },
      { value: "on_duty", label: "On duty" },
      { value: "work_from_home", label: "Work from home" },
      { value: "not_scheduled", label: "Not scheduled" },
    ],
  },
  PL_AUTH_METHOD: {
    code: "PL_AUTH_METHOD",
    name: "Authentication method",
    seededBy: "config",
    declared: 5,
    openSet: null,
    values: [
      { value: "sso_saml", label: "SSO (SAML)" },
      { value: "sso_oidc", label: "SSO (OIDC)" },
      { value: "password", label: "Password" },
      { value: "otp", label: "OTP" },
      { value: "biometric_device", label: "Biometric (device)" },
    ],
  },
  PL_AWARD_CATEGORY: {
    code: "PL_AWARD_CATEGORY",
    name: "Recognition category",
    seededBy: "config",
    declared: 8,
    openSet: null,
    values: [
      { value: "star_performer", label: "Star performer" },
      { value: "safety_champion", label: "Safety champion" },
      { value: "quality_champion", label: "Quality champion" },
      { value: "innovation", label: "Innovation" },
      { value: "long_service", label: "Long service" },
      { value: "team_award", label: "Team award" },
      { value: "customer_delight", label: "Customer delight" },
      { value: "spot_award", label: "Spot award" },
    ],
  },
  PL_BANK_FORMAT: {
    code: "PL_BANK_FORMAT",
    name: "Bank file format",
    seededBy: "config",
    declared: 8,
    openSet: null,
    values: [
      { value: "hdfc_enet", label: "HDFC ENet" },
      { value: "icici_cib", label: "ICICI CIB" },
      { value: "sbi_cinb", label: "SBI CINB" },
      { value: "axis_corporate", label: "Axis Corporate" },
      { value: "kotak_fyn", label: "Kotak FYN" },
      { value: "yes_bank", label: "Yes Bank" },
      { value: "npci_nach", label: "NPCI NACH" },
      { value: "generic_csv", label: "Generic CSV" },
    ],
  },
  PL_BLOOD_GROUP: {
    code: "PL_BLOOD_GROUP",
    name: "Blood group",
    seededBy: "system",
    declared: 9,
    openSet: null,
    values: [
      { value: "a_positive", label: "A+" },
      { value: "a_negative", label: "A-" },
      { value: "b_positive", label: "B+" },
      { value: "b_negative", label: "B-" },
      { value: "ab_positive", label: "AB+" },
      { value: "ab_negative", label: "AB-" },
      { value: "o_positive", label: "O+" },
      { value: "o_negative", label: "O-" },
      { value: "not_known", label: "Not known" },
    ],
  },
  PL_CALC_METHOD: {
    code: "PL_CALC_METHOD",
    name: "Calculation method",
    seededBy: "config",
    declared: 6,
    openSet: null,
    values: [
      { value: "fixed_amount", label: "Fixed amount" },
      { value: "percentage_of_component", label: "Percentage of component" },
      { value: "formula", label: "Formula" },
      { value: "slab_table", label: "Slab table" },
      { value: "attendance_driven", label: "Attendance driven" },
      { value: "rate_x_quantity", label: "Rate x quantity" },
    ],
  },
  PL_CANDIDATE_STAGE: {
    code: "PL_CANDIDATE_STAGE",
    name: "Candidate stage",
    seededBy: "config",
    declared: 11,
    openSet: null,
    values: [
      { value: "applied", label: "Applied" },
      { value: "screened", label: "Screened" },
      { value: "interview_scheduled", label: "Interview scheduled" },
      { value: "interview_complete", label: "Interview complete" },
      { value: "selected", label: "Selected" },
      { value: "offered", label: "Offered" },
      { value: "offer_accepted", label: "Offer accepted" },
      { value: "joined", label: "Joined" },
      { value: "rejected", label: "Rejected" },
      { value: "withdrawn", label: "Withdrawn" },
      { value: "on_hold", label: "On hold" },
    ],
  },
  PL_CAP_STATUS: {
    code: "PL_CAP_STATUS",
    name: "Statutory cap status",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "within_limit", label: "Within limit" },
      { value: "approaching_limit", label: "Approaching limit" },
      { value: "breach", label: "Breach" },
    ],
  },
  /**
   * The one vocabulary here that is not from the forms workbook. The client's demo build sheet
   * states it as EN_BREAK_TYPE (Config) for the break register RL-03 requires, and the registry
   * is where a dropdown belongs — carrying it anywhere else would be the second copy this file
   * exists to prevent.
   */
  PL_BREAK_TYPE: {
    code: "PL_BREAK_TYPE",
    name: "Break type",
    seededBy: "config",
    declared: 5,
    openSet: null,
    values: [
      { value: "meal", label: "Meal" },
      { value: "personal", label: "Personal" },
      { value: "gate_pass", label: "Gate pass" },
      { value: "shift_break", label: "Shift break" },
      { value: "unclassified", label: "Unclassified" },
    ],
  },
  PL_CLAIM_TYPE: {
    code: "PL_CLAIM_TYPE",
    name: "Reimbursement claim type",
    seededBy: "config",
    declared: 9,
    openSet: null,
    values: [
      { value: "fuel_conveyance", label: "Fuel / conveyance" },
      { value: "telephone_internet", label: "Telephone / internet" },
      { value: "medical", label: "Medical" },
      { value: "books_and_periodicals", label: "Books and periodicals" },
      { value: "travel", label: "Travel" },
      { value: "relocation", label: "Relocation" },
      { value: "professional_development", label: "Professional development" },
      { value: "meal", label: "Meal" },
      { value: "other", label: "Other" },
    ],
  },
  PL_CLEARANCE_ITEM_STATUS: {
    code: "PL_CLEARANCE_ITEM_STATUS",
    name: "Clearance item status",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "open", label: "Open" },
      { value: "cleared", label: "Cleared" },
      { value: "waived", label: "Waived" },
    ],
  },
  PL_CLEARANCE_STATUS: {
    code: "PL_CLEARANCE_STATUS",
    name: "Clearance status",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "not_started", label: "Not started" },
      { value: "in_progress", label: "In progress" },
      { value: "blocked", label: "Blocked" },
      { value: "cleared", label: "Cleared" },
    ],
  },
  PL_COMPONENT_TYPE: {
    code: "PL_COMPONENT_TYPE",
    name: "Pay component type",
    seededBy: "config",
    declared: 5,
    openSet: null,
    values: [
      { value: "earning", label: "Earning" },
      { value: "deduction", label: "Deduction" },
      { value: "employer_contribution", label: "Employer contribution" },
      { value: "reimbursement", label: "Reimbursement" },
      { value: "information_only", label: "Information only" },
    ],
  },
  PL_CONFIRMATION_ACTION: {
    code: "PL_CONFIRMATION_ACTION",
    name: "Confirmation action",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "confirm", label: "Confirm" },
      { value: "extend_probation", label: "Extend probation" },
      { value: "terminate", label: "Terminate" },
    ],
  },
  PL_CONFLICT_POLICY: {
    code: "PL_CONFLICT_POLICY",
    name: "Conflict policy",
    seededBy: "config",
    declared: 3,
    openSet: null,
    values: [
      { value: "owner_wins", label: "Owner wins" },
      { value: "hold_for_review", label: "Hold for review" },
      { value: "latest_wins", label: "Latest wins" },
    ],
  },
  PL_COUNTRY: {
    code: "PL_COUNTRY",
    name: "Country",
    seededBy: "system",
    declared: 2,
    openSet: "full ISO 3166-1 list seeded at install",
    values: [
      { value: "india", label: "India" },
    ],
  },
  PL_CURRENCY: {
    code: "PL_CURRENCY",
    name: "Currency",
    seededBy: "system",
    declared: 7,
    openSet: "full ISO 4217 list seeded at install",
    values: [
      { value: "inr", label: "INR" },
      { value: "usd", label: "USD" },
      { value: "eur", label: "EUR" },
      { value: "gbp", label: "GBP" },
      { value: "aed", label: "AED" },
      { value: "sgd", label: "SGD" },
    ],
  },
  PL_DAY_TYPE: {
    code: "PL_DAY_TYPE",
    name: "Day type",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "working_day", label: "Working day" },
      { value: "weekly_off_rest_day", label: "Weekly off / rest day" },
      { value: "holiday", label: "Holiday" },
      { value: "national_holiday", label: "National holiday" },
    ],
  },
  PL_DECISION: {
    code: "PL_DECISION",
    name: "Approval decision",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "approve", label: "Approve" },
      { value: "reject", label: "Reject" },
      { value: "return_for_correction", label: "Return for correction" },
      { value: "delegate", label: "Delegate" },
    ],
  },
  PL_DECLARATION_STATUS: {
    code: "PL_DECLARATION_STATUS",
    name: "Declaration status",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "draft", label: "Draft" },
      { value: "submitted", label: "Submitted" },
      { value: "proof_pending", label: "Proof pending" },
      { value: "verified", label: "Verified" },
      { value: "partially_verified", label: "Partially verified" },
    ],
  },
  PL_DECLINE_REASON: {
    code: "PL_DECLINE_REASON",
    name: "Offer decline reason",
    seededBy: "config",
    declared: 8,
    openSet: null,
    values: [
      { value: "compensation", label: "Compensation" },
      { value: "counter_offer_accepted", label: "Counter offer accepted" },
      { value: "role_mismatch", label: "Role mismatch" },
      { value: "location", label: "Location" },
      { value: "joining_date", label: "Joining date" },
      { value: "family_reasons", label: "Family reasons" },
      { value: "other_offer", label: "Other offer" },
      { value: "not_disclosed", label: "Not disclosed" },
    ],
  },
  PL_DISABILITY_TYPE: {
    code: "PL_DISABILITY_TYPE",
    name: "Disability type",
    seededBy: "system",
    declared: 7,
    openSet: null,
    values: [
      { value: "locomotor", label: "Locomotor" },
      { value: "visual", label: "Visual" },
      { value: "hearing", label: "Hearing" },
      { value: "speech", label: "Speech" },
      { value: "intellectual", label: "Intellectual" },
      { value: "multiple", label: "Multiple" },
      { value: "other", label: "Other" },
    ],
  },
  PL_DOCUMENT_CLASS: {
    code: "PL_DOCUMENT_CLASS",
    name: "Document class",
    seededBy: "config",
    declared: 17,
    openSet: null,
    values: [
      { value: "aadhaar", label: "Aadhaar" },
      { value: "pan", label: "PAN" },
      { value: "passport", label: "Passport" },
      { value: "driving_licence", label: "Driving licence" },
      { value: "voter_id", label: "Voter ID" },
      { value: "bank_proof", label: "Bank proof" },
      { value: "educational_certificate", label: "Educational certificate" },
      { value: "experience_letter", label: "Experience letter" },
      { value: "relieving_letter", label: "Relieving letter" },
      { value: "payslip_previous_employer", label: "Payslip (previous employer)" },
      { value: "medical_fitness_certificate", label: "Medical fitness certificate" },
      { value: "disability_certificate", label: "Disability certificate" },
      { value: "photograph", label: "Photograph" },
      { value: "signature", label: "Signature" },
      { value: "police_verification", label: "Police verification" },
      { value: "contract_agreement", label: "Contract / agreement" },
      { value: "other", label: "Other" },
    ],
  },
  PL_EDUCATION_LEVEL: {
    code: "PL_EDUCATION_LEVEL",
    name: "Qualification level",
    seededBy: "config",
    declared: 9,
    openSet: null,
    values: [
      { value: "below_10th", label: "Below 10th" },
      { value: "10th_sslc", label: "10th / SSLC" },
      { value: "12th_puc", label: "12th / PUC" },
      { value: "iti", label: "ITI" },
      { value: "diploma", label: "Diploma" },
      { value: "graduate", label: "Graduate" },
      { value: "post_graduate", label: "Post graduate" },
      { value: "doctorate", label: "Doctorate" },
      { value: "professional_certification", label: "Professional certification" },
    ],
  },
  PL_EMPLOYMENT_TYPE: {
    code: "PL_EMPLOYMENT_TYPE",
    name: "Employment type",
    seededBy: "config",
    declared: 10,
    openSet: null,
    values: [
      { value: "permanent", label: "Permanent" },
      { value: "probation", label: "Probation" },
      { value: "fixed_term_contract", label: "Fixed term contract" },
      { value: "trainee", label: "Trainee" },
      { value: "apprentice_naps_nats", label: "Apprentice (NAPS/NATS)" },
      { value: "intern", label: "Intern" },
      { value: "retainer", label: "Retainer" },
      { value: "consultant", label: "Consultant" },
      { value: "contract_through_vendor", label: "Contract (through vendor)" },
      { value: "part_time", label: "Part time" },
    ],
  },
  PL_ENCASHMENT_BASIS: {
    code: "PL_ENCASHMENT_BASIS",
    name: "Encashment rate basis",
    seededBy: "config",
    declared: 3,
    openSet: null,
    values: [
      { value: "basic", label: "Basic" },
      { value: "basic_da", label: "Basic + DA" },
      { value: "gross", label: "Gross" },
    ],
  },
  PL_ENTITY_TYPE: {
    code: "PL_ENTITY_TYPE",
    name: "Legal entity type",
    seededBy: "config",
    declared: 8,
    openSet: null,
    values: [
      { value: "private_limited", label: "Private Limited" },
      { value: "public_limited", label: "Public Limited" },
      { value: "llp", label: "LLP" },
      { value: "partnership", label: "Partnership" },
      { value: "proprietorship", label: "Proprietorship" },
      { value: "society", label: "Society" },
      { value: "trust", label: "Trust" },
      { value: "branch_office", label: "Branch Office" },
    ],
  },
  PL_ERP_SYSTEM: {
    code: "PL_ERP_SYSTEM",
    name: "ERP system",
    seededBy: "config",
    declared: 6,
    openSet: null,
    values: [
      { value: "sap", label: "SAP" },
      { value: "oracle", label: "Oracle" },
      { value: "microsoft_dynamics", label: "Microsoft Dynamics" },
      { value: "tally", label: "Tally" },
      { value: "odoo", label: "Odoo" },
      { value: "custom_file_based", label: "Custom / file based" },
    ],
  },
  PL_ESTB_TYPE: {
    code: "PL_ESTB_TYPE",
    name: "Establishment type",
    seededBy: "config",
    declared: 8,
    openSet: null,
    values: [
      { value: "factory", label: "Factory" },
      { value: "shops_and_establishment", label: "Shops & Establishment" },
      { value: "mine", label: "Mine" },
      { value: "plantation", label: "Plantation" },
      { value: "motor_transport", label: "Motor Transport" },
      { value: "construction", label: "Construction" },
      { value: "beedi_and_cigar", label: "Beedi & Cigar" },
      { value: "contract_establishment", label: "Contract Establishment" },
    ],
  },
  PL_EXCEPTION_ACTION: {
    code: "PL_EXCEPTION_ACTION",
    name: "Exception resolution action",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "accept_proposal", label: "Accept proposal" },
      { value: "amend", label: "Amend" },
      { value: "reject", label: "Reject" },
      { value: "escalate", label: "Escalate" },
    ],
  },
  PL_EXCEPTION_TYPE: {
    code: "PL_EXCEPTION_TYPE",
    name: "Attendance exception type",
    seededBy: "system",
    declared: 8,
    openSet: null,
    values: [
      { value: "unpaired_punch", label: "Unpaired punch" },
      { value: "missing_attendance_day", label: "Missing attendance day" },
      { value: "device_failure", label: "Device failure" },
      { value: "shift_inferred", label: "Shift inferred" },
      { value: "geofence_breach", label: "Geofence breach" },
      { value: "duplicate_punch", label: "Duplicate punch" },
      { value: "punch_outside_roster", label: "Punch outside roster" },
      { value: "late_beyond_allowance", label: "Late beyond allowance" },
    ],
  },
  PL_EXEMPTION_SECTION: {
    code: "PL_EXEMPTION_SECTION",
    name: "Tax exemption section",
    seededBy: "system",
    declared: 8,
    openSet: null,
    values: [
      { value: "10_5_lta", label: "10(5) LTA" },
      { value: "10_13a_hra", label: "10(13A) HRA" },
      { value: "10_14_special_allowance", label: "10(14) special allowance" },
      { value: "16_ia_standard_deduction", label: "16(ia) standard deduction" },
      { value: "16_ii_entertainment", label: "16(ii) entertainment" },
      { value: "16_iii_professional_tax", label: "16(iii) professional tax" },
      { value: "17_2_perquisite", label: "17(2) perquisite" },
      { value: "not_exempt", label: "Not exempt" },
    ],
  },
  PL_EXIT_REASON: {
    code: "PL_EXIT_REASON",
    name: "Exit reason category",
    seededBy: "config",
    declared: 12,
    openSet: null,
    values: [
      { value: "better_opportunity", label: "Better opportunity" },
      { value: "compensation", label: "Compensation" },
      { value: "career_growth", label: "Career growth" },
      { value: "relocation", label: "Relocation" },
      { value: "higher_studies", label: "Higher studies" },
      { value: "personal_family", label: "Personal / family" },
      { value: "health", label: "Health" },
      { value: "work_environment", label: "Work environment" },
      { value: "manager_relationship", label: "Manager relationship" },
      { value: "performance", label: "Performance" },
      { value: "disciplinary", label: "Disciplinary" },
      { value: "not_disclosed", label: "Not disclosed" },
    ],
  },
  PL_EXIT_TYPE: {
    code: "PL_EXIT_TYPE",
    name: "Exit type",
    seededBy: "system",
    declared: 7,
    openSet: null,
    values: [
      { value: "resignation", label: "Resignation" },
      { value: "termination", label: "Termination" },
      { value: "retirement", label: "Retirement" },
      { value: "contract_end", label: "Contract end" },
      { value: "abandonment", label: "Abandonment" },
      { value: "death_in_service", label: "Death in service" },
      { value: "redundancy", label: "Redundancy" },
    ],
  },
  PL_FIELD_OWNER: {
    code: "PL_FIELD_OWNER",
    name: "Field owner",
    seededBy: "system",
    declared: 2,
    openSet: null,
    values: [
      { value: "nucleus", label: "Nucleus" },
      { value: "erp", label: "ERP" },
    ],
  },
  PL_FITNESS_STATUS: {
    code: "PL_FITNESS_STATUS",
    name: "Medical fitness status",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "fit", label: "Fit" },
      { value: "fit_with_restriction", label: "Fit with restriction" },
      { value: "unfit", label: "Unfit" },
      { value: "pending", label: "Pending" },
    ],
  },
  PL_FLAG_DISPOSITION: {
    code: "PL_FLAG_DISPOSITION",
    name: "Audit flag disposition",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "resolve", label: "Resolve" },
      { value: "waive", label: "Waive" },
      { value: "escalate", label: "Escalate" },
    ],
  },
  PL_FREQUENCY: {
    code: "PL_FREQUENCY",
    name: "Frequency",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "monthly", label: "Monthly" },
      { value: "quarterly", label: "Quarterly" },
      { value: "half_yearly", label: "Half-yearly" },
      { value: "annual", label: "Annual" },
      { value: "event_based", label: "Event-based" },
    ],
  },
  PL_GATE_PASS_TYPE: {
    code: "PL_GATE_PASS_TYPE",
    name: "Gate pass type",
    seededBy: "config",
    declared: 2,
    openSet: null,
    values: [
      { value: "personal", label: "Personal" },
      { value: "official", label: "Official" },
    ],
  },
  PL_GENDER: {
    code: "PL_GENDER",
    name: "Gender",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
      { value: "other", label: "Other" },
      { value: "prefer_not_to_say", label: "Prefer not to say" },
    ],
  },
  PL_GEOFENCE_RESULT: {
    code: "PL_GEOFENCE_RESULT",
    name: "Geofence result",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "inside", label: "Inside" },
      { value: "outside", label: "Outside" },
      { value: "unavailable", label: "Unavailable" },
    ],
  },
  PL_HALF_DAY_SESSION: {
    code: "PL_HALF_DAY_SESSION",
    name: "Half day session",
    seededBy: "system",
    declared: 2,
    openSet: null,
    values: [
      { value: "first_half", label: "First half" },
      { value: "second_half", label: "Second half" },
    ],
  },
  PL_INTERVIEW_MODE: {
    code: "PL_INTERVIEW_MODE",
    name: "Interview mode",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "in_person", label: "In person" },
      { value: "video", label: "Video" },
      { value: "telephone", label: "Telephone" },
    ],
  },
  PL_INTERVIEW_ROUND: {
    code: "PL_INTERVIEW_ROUND",
    name: "Interview round",
    seededBy: "config",
    declared: 6,
    openSet: null,
    values: [
      { value: "screening", label: "Screening" },
      { value: "technical_1", label: "Technical 1" },
      { value: "technical_2", label: "Technical 2" },
      { value: "functional", label: "Functional" },
      { value: "hr", label: "HR" },
      { value: "final_leadership", label: "Final / leadership" },
    ],
  },
  PL_INTERVIEW_VERDICT: {
    code: "PL_INTERVIEW_VERDICT",
    name: "Interview verdict",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "strong_hire", label: "Strong hire" },
      { value: "hire", label: "Hire" },
      { value: "hold", label: "Hold" },
      { value: "no_hire", label: "No hire" },
    ],
  },
  PL_LANGUAGE: {
    code: "PL_LANGUAGE",
    name: "Language",
    seededBy: "config",
    declared: 14,
    openSet: null,
    values: [
      { value: "english", label: "English" },
      { value: "hindi", label: "Hindi" },
      { value: "kannada", label: "Kannada" },
      { value: "tamil", label: "Tamil" },
      { value: "telugu", label: "Telugu" },
      { value: "malayalam", label: "Malayalam" },
      { value: "marathi", label: "Marathi" },
      { value: "gujarati", label: "Gujarati" },
      { value: "bengali", label: "Bengali" },
      { value: "odia", label: "Odia" },
      { value: "punjabi", label: "Punjabi" },
      { value: "assamese", label: "Assamese" },
      { value: "urdu", label: "Urdu" },
      { value: "other", label: "Other" },
    ],
  },
  PL_LEAVE_TYPE: {
    code: "PL_LEAVE_TYPE",
    name: "Leave type",
    seededBy: "config",
    declared: 11,
    openSet: null,
    values: [
      { value: "earned_leave", label: "Earned leave" },
      { value: "casual_leave", label: "Casual leave" },
      { value: "sick_leave", label: "Sick leave" },
      { value: "maternity_leave", label: "Maternity leave" },
      { value: "paternity_leave", label: "Paternity leave" },
      { value: "compensatory_off", label: "Compensatory off" },
      { value: "leave_without_pay", label: "Leave without pay" },
      { value: "bereavement_leave", label: "Bereavement leave" },
      { value: "marriage_leave", label: "Marriage leave" },
      { value: "birthday_leave", label: "Birthday leave" },
      { value: "special_leave", label: "Special leave" },
    ],
  },
  PL_LEAVE_UNIT: {
    code: "PL_LEAVE_UNIT",
    name: "Leave unit",
    seededBy: "config",
    declared: 2,
    openSet: null,
    values: [
      { value: "days", label: "Days" },
      { value: "hours", label: "Hours" },
    ],
  },
  PL_LETTER_TYPE: {
    code: "PL_LETTER_TYPE",
    name: "Letter type",
    seededBy: "config",
    declared: 14,
    openSet: null,
    values: [
      { value: "offer", label: "Offer" },
      { value: "appointment", label: "Appointment" },
      { value: "confirmation", label: "Confirmation" },
      { value: "salary_revision", label: "Salary revision" },
      { value: "promotion", label: "Promotion" },
      { value: "transfer", label: "Transfer" },
      { value: "warning", label: "Warning" },
      { value: "show_cause", label: "Show cause" },
      { value: "experience", label: "Experience" },
      { value: "relieving", label: "Relieving" },
      { value: "no_objection_certificate", label: "No objection certificate" },
      { value: "address_proof", label: "Address proof" },
      { value: "bank_introduction", label: "Bank introduction" },
      { value: "visa_support", label: "Visa support" },
    ],
  },
  PL_LOAN_PURPOSE: {
    code: "PL_LOAN_PURPOSE",
    name: "Loan purpose",
    seededBy: "config",
    declared: 8,
    openSet: null,
    values: [
      { value: "medical", label: "Medical" },
      { value: "education", label: "Education" },
      { value: "housing", label: "Housing" },
      { value: "marriage", label: "Marriage" },
      { value: "vehicle", label: "Vehicle" },
      { value: "festival", label: "Festival" },
      { value: "personal", label: "Personal" },
      { value: "emergency", label: "Emergency" },
    ],
  },
  PL_LOCATION_TYPE: {
    code: "PL_LOCATION_TYPE",
    name: "Location type",
    seededBy: "config",
    declared: 11,
    openSet: null,
    values: [
      { value: "head_office", label: "Head office" },
      { value: "corporate_office", label: "Corporate office" },
      { value: "plant", label: "Plant" },
      { value: "factory", label: "Factory" },
      { value: "warehouse", label: "Warehouse" },
      { value: "depot", label: "Depot" },
      { value: "branch", label: "Branch" },
      { value: "site", label: "Site" },
      { value: "project_site", label: "Project site" },
      { value: "retail_outlet", label: "Retail outlet" },
      { value: "remote", label: "Remote" },
    ],
  },
  PL_MARITAL_STATUS: {
    code: "PL_MARITAL_STATUS",
    name: "Marital status",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "single", label: "Single" },
      { value: "married", label: "Married" },
      { value: "widowed", label: "Widowed" },
      { value: "divorced", label: "Divorced" },
      { value: "separated", label: "Separated" },
    ],
  },
  PL_MASTER_MODE: {
    code: "PL_MASTER_MODE",
    name: "Master data mode",
    seededBy: "config",
    declared: 3,
    openSet: null,
    values: [
      { value: "nucleus_owns", label: "Nucleus owns" },
      { value: "erp_owns", label: "ERP owns" },
      { value: "co_owned", label: "Co-owned" },
    ],
  },
  PL_MATURITY_STATUS: {
    code: "PL_MATURITY_STATUS",
    name: "Referral award maturity",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "pending", label: "Pending" },
      { value: "part_matured", label: "Part matured" },
      { value: "fully_matured", label: "Fully matured" },
      { value: "forfeited", label: "Forfeited" },
    ],
  },
  PL_MONTH: {
    code: "PL_MONTH",
    name: "Month",
    seededBy: "system",
    declared: 12,
    openSet: null,
    values: [
      { value: "january", label: "January" },
      { value: "february", label: "February" },
      { value: "march", label: "March" },
      { value: "april", label: "April" },
      { value: "may", label: "May" },
      { value: "june", label: "June" },
      { value: "july", label: "July" },
      { value: "august", label: "August" },
      { value: "september", label: "September" },
      { value: "october", label: "October" },
      { value: "november", label: "November" },
      { value: "december", label: "December" },
    ],
  },
  PL_NATIONALITY: {
    code: "PL_NATIONALITY",
    name: "Nationality",
    seededBy: "system",
    declared: 2,
    openSet: "derived from the ISO 3166-1 country list",
    values: [
      { value: "indian", label: "Indian" },
    ],
  },
  PL_NOMINEE_SCHEME: {
    code: "PL_NOMINEE_SCHEME",
    name: "Nominee scheme",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "provident_fund", label: "Provident fund" },
      { value: "gratuity", label: "Gratuity" },
      { value: "group_insurance", label: "Group insurance" },
      { value: "superannuation", label: "Superannuation" },
      { value: "esi_dependant", label: "ESI dependant" },
    ],
  },
  PL_OBLIGATION_STATUS: {
    code: "PL_OBLIGATION_STATUS",
    name: "Obligation status",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "open", label: "Open" },
      { value: "in_progress", label: "In progress" },
      { value: "filed", label: "Filed" },
      { value: "filed_late", label: "Filed late" },
      { value: "not_applicable", label: "Not applicable" },
    ],
  },
  PL_OFFER_RESPONSE: {
    code: "PL_OFFER_RESPONSE",
    name: "Offer response",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "pending", label: "Pending" },
      { value: "accepted", label: "Accepted" },
      { value: "declined", label: "Declined" },
      { value: "negotiating", label: "Negotiating" },
      { value: "lapsed", label: "Lapsed" },
    ],
  },
  PL_OT_BASIS: {
    code: "PL_OT_BASIS",
    name: "Overtime basis",
    seededBy: "config",
    declared: 2,
    openSet: null,
    values: [
      { value: "gross_minutes", label: "Gross minutes" },
      { value: "net_minutes", label: "Net minutes" },
    ],
  },
  PL_OT_ELIGIBILITY: {
    code: "PL_OT_ELIGIBILITY",
    name: "Overtime eligibility",
    seededBy: "config",
    declared: 4,
    openSet: null,
    values: [
      { value: "always", label: "Always" },
      { value: "rest_day_and_holiday_only", label: "Rest day and holiday only" },
      { value: "beyond_weekly_hours_only", label: "Beyond weekly hours only" },
      { value: "none", label: "None" },
    ],
  },
  PL_PAYMENT_MODE: {
    code: "PL_PAYMENT_MODE",
    name: "Payment mode",
    seededBy: "config",
    declared: 6,
    openSet: null,
    values: [
      { value: "bank_transfer_neft", label: "Bank transfer (NEFT)" },
      { value: "bank_transfer_imps", label: "Bank transfer (IMPS)" },
      { value: "bank_transfer_rtgs", label: "Bank transfer (RTGS)" },
      { value: "cheque", label: "Cheque" },
      { value: "cash", label: "Cash" },
      { value: "demand_draft", label: "Demand draft" },
    ],
  },
  PL_PERSON_STATUS: {
    code: "PL_PERSON_STATUS",
    name: "Person record status",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "draft", label: "Draft" },
      { value: "active", label: "Active" },
      { value: "suspended", label: "Suspended" },
      { value: "on_notice", label: "On notice" },
      { value: "exited", label: "Exited" },
    ],
  },
  PL_POSITION_STATUS: {
    code: "PL_POSITION_STATUS",
    name: "Position status",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "vacant", label: "Vacant" },
      { value: "filled", label: "Filled" },
      { value: "frozen", label: "Frozen" },
      { value: "abolished", label: "Abolished" },
    ],
  },
  PL_PRINCIPAL_TYPE: {
    code: "PL_PRINCIPAL_TYPE",
    name: "Principal type",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "user", label: "User" },
      { value: "service_account", label: "Service account" },
      { value: "agent", label: "Agent" },
    ],
  },
  PL_PRIORITY: {
    code: "PL_PRIORITY",
    name: "Priority",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "low", label: "Low" },
      { value: "normal", label: "Normal" },
      { value: "high", label: "High" },
      { value: "urgent", label: "Urgent" },
    ],
  },
  PL_PROOF_STATUS: {
    code: "PL_PROOF_STATUS",
    name: "Proof verification status",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "pending", label: "Pending" },
      { value: "accepted", label: "Accepted" },
      { value: "rejected", label: "Rejected" },
      { value: "partially_accepted", label: "Partially accepted" },
    ],
  },
  PL_PRORATION_BASIS: {
    code: "PL_PRORATION_BASIS",
    name: "Proration basis",
    seededBy: "config",
    declared: 3,
    openSet: null,
    values: [
      { value: "calendar_days", label: "Calendar days" },
      { value: "payable_days", label: "Payable days" },
      { value: "working_days", label: "Working days" },
    ],
  },
  PL_PUBLISH_STATUS: {
    code: "PL_PUBLISH_STATUS",
    name: "Roster publish status",
    seededBy: "system",
    declared: 2,
    openSet: null,
    values: [
      { value: "draft", label: "Draft" },
      { value: "published", label: "Published" },
    ],
  },
  PL_PUNCH_DIRECTION: {
    code: "PL_PUNCH_DIRECTION",
    name: "Punch direction",
    seededBy: "system",
    declared: 2,
    openSet: null,
    values: [
      { value: "in", label: "IN" },
      { value: "out", label: "OUT" },
    ],
  },
  PL_PUNCH_SOURCE: {
    code: "PL_PUNCH_SOURCE",
    name: "Punch source",
    seededBy: "system",
    declared: 6,
    openSet: null,
    values: [
      { value: "biometric_device", label: "Biometric device" },
      { value: "mobile_app", label: "Mobile app" },
      { value: "kiosk", label: "Kiosk" },
      { value: "whatsapp", label: "WhatsApp" },
      { value: "web", label: "Web" },
      { value: "manual_regularised", label: "Manual (regularised)" },
    ],
  },
  PL_RATING_SCALE: {
    code: "PL_RATING_SCALE",
    name: "Rating scale",
    seededBy: "config",
    declared: 5,
    openSet: null,
    values: [
      { value: "outstanding", label: "Outstanding" },
      { value: "exceeds_expectations", label: "Exceeds expectations" },
      { value: "meets_expectations", label: "Meets expectations" },
      { value: "needs_improvement", label: "Needs improvement" },
      { value: "unsatisfactory", label: "Unsatisfactory" },
    ],
  },
  PL_REFERRAL_RELATION: {
    code: "PL_REFERRAL_RELATION",
    name: "Referrer relationship",
    seededBy: "config",
    declared: 6,
    openSet: null,
    values: [
      { value: "former_colleague", label: "Former colleague" },
      { value: "friend", label: "Friend" },
      { value: "relative", label: "Relative" },
      { value: "academic_contact", label: "Academic contact" },
      { value: "professional_network", label: "Professional network" },
      { value: "other", label: "Other" },
    ],
  },
  PL_REGISTRATION_STATUS: {
    code: "PL_REGISTRATION_STATUS",
    name: "Statutory registration status",
    seededBy: "system",
    declared: 4,
    openSet: null,
    values: [
      { value: "not_required", label: "Not required" },
      { value: "pending", label: "Pending" },
      { value: "registered", label: "Registered" },
      { value: "failed", label: "Failed" },
    ],
  },
  PL_REGULARISATION_TYPE: {
    code: "PL_REGULARISATION_TYPE",
    name: "Regularisation type",
    seededBy: "config",
    declared: 6,
    openSet: null,
    values: [
      { value: "missing_punch", label: "Missing punch" },
      { value: "wrong_shift_applied", label: "Wrong shift applied" },
      { value: "on_duty", label: "On duty" },
      { value: "work_from_home", label: "Work from home" },
      { value: "late_waiver", label: "Late waiver" },
      { value: "device_failure", label: "Device failure" },
    ],
  },
  PL_REHIRE_ELIGIBILITY: {
    code: "PL_REHIRE_ELIGIBILITY",
    name: "Rehire eligibility",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "with_approval", label: "With approval" },
    ],
  },
  PL_REJECTION_REASON: {
    code: "PL_REJECTION_REASON",
    name: "Candidate rejection reason",
    seededBy: "config",
    declared: 9,
    openSet: null,
    values: [
      { value: "skill_mismatch", label: "Skill mismatch" },
      { value: "experience_mismatch", label: "Experience mismatch" },
      { value: "compensation_mismatch", label: "Compensation mismatch" },
      { value: "location_constraint", label: "Location constraint" },
      { value: "notice_period", label: "Notice period" },
      { value: "failed_assessment", label: "Failed assessment" },
      { value: "background_check", label: "Background check" },
      { value: "position_closed", label: "Position closed" },
      { value: "other", label: "Other" },
    ],
  },
  PL_RELATION: {
    code: "PL_RELATION",
    name: "Relationship",
    seededBy: "system",
    declared: 14,
    openSet: null,
    values: [
      { value: "spouse", label: "Spouse" },
      { value: "father", label: "Father" },
      { value: "mother", label: "Mother" },
      { value: "son", label: "Son" },
      { value: "daughter", label: "Daughter" },
      { value: "brother", label: "Brother" },
      { value: "sister", label: "Sister" },
      { value: "father_in_law", label: "Father-in-law" },
      { value: "mother_in_law", label: "Mother-in-law" },
      { value: "grandfather", label: "Grandfather" },
      { value: "grandmother", label: "Grandmother" },
      { value: "guardian", label: "Guardian" },
      { value: "friend", label: "Friend" },
      { value: "other", label: "Other" },
    ],
  },
  PL_RELEASE_CHANNEL: {
    code: "PL_RELEASE_CHANNEL",
    name: "Delivery channel",
    seededBy: "config",
    declared: 4,
    openSet: null,
    values: [
      { value: "email", label: "Email" },
      { value: "employee_portal", label: "Employee portal" },
      { value: "whatsapp", label: "WhatsApp" },
      { value: "printed_copy", label: "Printed copy" },
    ],
  },
  PL_RELIGION: {
    code: "PL_RELIGION",
    name: "Religion",
    seededBy: "config",
    declared: 10,
    openSet: null,
    values: [
      { value: "hindu", label: "Hindu" },
      { value: "muslim", label: "Muslim" },
      { value: "christian", label: "Christian" },
      { value: "sikh", label: "Sikh" },
      { value: "buddhist", label: "Buddhist" },
      { value: "jain", label: "Jain" },
      { value: "parsi", label: "Parsi" },
      { value: "jewish", label: "Jewish" },
      { value: "other", label: "Other" },
      { value: "not_disclosed", label: "Not disclosed" },
    ],
  },
  PL_REQUISITION_TYPE: {
    code: "PL_REQUISITION_TYPE",
    name: "Requisition type",
    seededBy: "system",
    declared: 2,
    openSet: null,
    values: [
      { value: "replacement", label: "Replacement" },
      { value: "addition", label: "Addition" },
    ],
  },
  PL_REST_DAY_PATTERN: {
    code: "PL_REST_DAY_PATTERN",
    name: "Rest day pattern",
    seededBy: "config",
    declared: 4,
    openSet: null,
    values: [
      { value: "fixed_weekly_day", label: "Fixed weekly day" },
      { value: "two_fixed_days", label: "Two fixed days" },
      { value: "rotating", label: "Rotating" },
      { value: "none", label: "None" },
    ],
  },
  PL_REVISION_TYPE: {
    code: "PL_REVISION_TYPE",
    name: "Salary revision type",
    seededBy: "config",
    declared: 7,
    openSet: null,
    values: [
      { value: "annual_increment", label: "Annual increment" },
      { value: "promotion", label: "Promotion" },
      { value: "market_correction", label: "Market correction" },
      { value: "wage_settlement", label: "Wage settlement" },
      { value: "data_correction", label: "Data correction" },
      { value: "retention", label: "Retention" },
      { value: "confirmation", label: "Confirmation" },
    ],
  },
  PL_ROLE: {
    code: "PL_ROLE",
    name: "Role",
    seededBy: "config",
    declared: 22,
    openSet: null,
    values: [
      { value: "tenant_admin", label: "Tenant admin" },
      { value: "hr_head", label: "HR head" },
      { value: "hr_ops", label: "HR ops" },
      { value: "hr_business_partner", label: "HR business partner" },
      { value: "payroll_manager", label: "Payroll manager" },
      { value: "payroll_executive", label: "Payroll executive" },
      { value: "finance", label: "Finance" },
      { value: "compliance_owner", label: "Compliance owner" },
      { value: "compliance_engineer", label: "Compliance engineer" },
      { value: "implementation_consultant", label: "Implementation consultant" },
      { value: "plant_hr", label: "Plant HR" },
      { value: "supervisor", label: "Supervisor" },
      { value: "manager", label: "Manager" },
      { value: "employee", label: "Employee" },
      { value: "security_gate", label: "Security / gate" },
      { value: "admin_facilities", label: "Admin / facilities" },
      { value: "it_admin", label: "IT admin" },
      { value: "auditor_read_only", label: "Auditor (read only)" },
      { value: "director", label: "Director" },
      { value: "recruiter", label: "Recruiter" },
      { value: "interviewer", label: "Interviewer" },
      { value: "vendor_coordinator", label: "Vendor coordinator" },
    ],
  },
  PL_ROUNDING: {
    code: "PL_ROUNDING",
    name: "Rounding rule",
    seededBy: "config",
    declared: 4,
    openSet: null,
    values: [
      { value: "nearest_rupee", label: "Nearest rupee" },
      { value: "round_up", label: "Round up" },
      { value: "round_down", label: "Round down" },
      { value: "no_rounding", label: "No rounding" },
    ],
  },
  PL_RUN_STATE: {
    code: "PL_RUN_STATE",
    name: "Payroll run state",
    seededBy: "system",
    declared: 9,
    openSet: null,
    values: [
      { value: "draft", label: "Draft" },
      { value: "inputs_locked", label: "Inputs locked" },
      { value: "calculated", label: "Calculated" },
      { value: "audited", label: "Audited" },
      { value: "approved", label: "Approved" },
      { value: "disbursement_prepared", label: "Disbursement prepared" },
      { value: "disbursed", label: "Disbursed" },
      { value: "posted_to_gl", label: "Posted to GL" },
      { value: "closed", label: "Closed" },
    ],
  },
  PL_RUN_TYPE: {
    code: "PL_RUN_TYPE",
    name: "Payroll run type",
    seededBy: "system",
    declared: 6,
    openSet: null,
    values: [
      { value: "regular", label: "Regular" },
      { value: "off_cycle_overtime", label: "Off-cycle overtime" },
      { value: "arrears", label: "Arrears" },
      { value: "full_and_final", label: "Full and final" },
      { value: "bonus", label: "Bonus" },
      { value: "reimbursement", label: "Reimbursement" },
    ],
  },
  PL_SALUTATION: {
    code: "PL_SALUTATION",
    name: "Salutation",
    seededBy: "config",
    declared: 7,
    openSet: null,
    values: [
      { value: "mr", label: "Mr." },
      { value: "ms", label: "Ms." },
      { value: "mrs", label: "Mrs." },
      { value: "dr", label: "Dr." },
      { value: "prof", label: "Prof." },
      { value: "shri", label: "Shri" },
      { value: "smt", label: "Smt." },
    ],
  },
  PL_SANDWICH_RULE: {
    code: "PL_SANDWICH_RULE",
    name: "Sandwich rule",
    seededBy: "config",
    declared: 4,
    openSet: null,
    values: [
      { value: "exclude_holidays_and_rest_days", label: "Exclude holidays and rest days" },
      { value: "include_holidays", label: "Include holidays" },
      { value: "include_rest_days", label: "Include rest days" },
      { value: "include_both", label: "Include both" },
    ],
  },
  PL_SETTLEMENT_STATUS: {
    code: "PL_SETTLEMENT_STATUS",
    name: "Settlement status",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "draft", label: "Draft" },
      { value: "computed", label: "Computed" },
      { value: "approved", label: "Approved" },
      { value: "paid", label: "Paid" },
      { value: "recovery_pending", label: "Recovery pending" },
    ],
  },
  PL_SEVERITY: {
    code: "PL_SEVERITY",
    name: "Severity",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "critical", label: "Critical" },
      { value: "warning", label: "Warning" },
      { value: "info", label: "Info" },
    ],
  },
  PL_SOCIAL_CATEGORY: {
    code: "PL_SOCIAL_CATEGORY",
    name: "Social category",
    seededBy: "system",
    declared: 6,
    openSet: null,
    values: [
      { value: "general", label: "General" },
      { value: "obc", label: "OBC" },
      { value: "sc", label: "SC" },
      { value: "st", label: "ST" },
      { value: "ews", label: "EWS" },
      { value: "not_disclosed", label: "Not disclosed" },
    ],
  },
  PL_SOURCE_CHANNEL: {
    code: "PL_SOURCE_CHANNEL",
    name: "Candidate source",
    seededBy: "config",
    declared: 9,
    openSet: null,
    values: [
      { value: "employee_referral", label: "Employee referral" },
      { value: "job_portal", label: "Job portal" },
      { value: "recruitment_agency", label: "Recruitment agency" },
      { value: "walk_in", label: "Walk-in" },
      { value: "campus", label: "Campus" },
      { value: "internal_transfer", label: "Internal transfer" },
      { value: "social_media", label: "Social media" },
      { value: "direct_application", label: "Direct application" },
      { value: "rehire", label: "Rehire" },
    ],
  },
  PL_STATE: {
    code: "PL_STATE",
    name: "Indian state / union territory",
    seededBy: "system",
    declared: 36,
    openSet: null,
    values: [
      { value: "andhra_pradesh", label: "Andhra Pradesh" },
      { value: "arunachal_pradesh", label: "Arunachal Pradesh" },
      { value: "assam", label: "Assam" },
      { value: "bihar", label: "Bihar" },
      { value: "chhattisgarh", label: "Chhattisgarh" },
      { value: "goa", label: "Goa" },
      { value: "gujarat", label: "Gujarat" },
      { value: "haryana", label: "Haryana" },
      { value: "himachal_pradesh", label: "Himachal Pradesh" },
      { value: "jharkhand", label: "Jharkhand" },
      { value: "karnataka", label: "Karnataka" },
      { value: "kerala", label: "Kerala" },
      { value: "madhya_pradesh", label: "Madhya Pradesh" },
      { value: "maharashtra", label: "Maharashtra" },
      { value: "manipur", label: "Manipur" },
      { value: "meghalaya", label: "Meghalaya" },
      { value: "mizoram", label: "Mizoram" },
      { value: "nagaland", label: "Nagaland" },
      { value: "odisha", label: "Odisha" },
      { value: "punjab", label: "Punjab" },
      { value: "rajasthan", label: "Rajasthan" },
      { value: "sikkim", label: "Sikkim" },
      { value: "tamil_nadu", label: "Tamil Nadu" },
      { value: "telangana", label: "Telangana" },
      { value: "tripura", label: "Tripura" },
      { value: "uttar_pradesh", label: "Uttar Pradesh" },
      { value: "uttarakhand", label: "Uttarakhand" },
      { value: "west_bengal", label: "West Bengal" },
      { value: "andaman_and_nicobar_islands", label: "Andaman & Nicobar Islands" },
      { value: "chandigarh", label: "Chandigarh" },
      { value: "dadra_and_nagar_haveli_and_daman_and_diu", label: "Dadra & Nagar Haveli and Daman & Diu" },
      { value: "delhi", label: "Delhi" },
      { value: "jammu_and_kashmir", label: "Jammu & Kashmir" },
      { value: "ladakh", label: "Ladakh" },
      { value: "lakshadweep", label: "Lakshadweep" },
      { value: "puducherry", label: "Puducherry" },
    ],
  },
  PL_SYNC_FREQUENCY: {
    code: "PL_SYNC_FREQUENCY",
    name: "Sync frequency",
    seededBy: "config",
    declared: 4,
    openSet: null,
    values: [
      { value: "real_time", label: "Real time" },
      { value: "hourly", label: "Hourly" },
      { value: "daily", label: "Daily" },
      { value: "on_demand", label: "On demand" },
    ],
  },
  PL_TASK_STATUS: {
    code: "PL_TASK_STATUS",
    name: "Task status",
    seededBy: "system",
    declared: 5,
    openSet: null,
    values: [
      { value: "open", label: "Open" },
      { value: "in_progress", label: "In progress" },
      { value: "done", label: "Done" },
      { value: "waived", label: "Waived" },
      { value: "overdue", label: "Overdue" },
    ],
  },
  PL_TAX_REGIME: {
    code: "PL_TAX_REGIME",
    name: "Tax regime",
    seededBy: "system",
    declared: 2,
    openSet: null,
    values: [
      { value: "old_regime", label: "Old regime" },
      { value: "new_regime", label: "New regime" },
    ],
  },
  PL_TEST_RESULT: {
    code: "PL_TEST_RESULT",
    name: "Compliance test result",
    seededBy: "system",
    declared: 2,
    openSet: null,
    values: [
      { value: "pass", label: "Pass" },
      { value: "fail", label: "Fail" },
    ],
  },
  PL_TICKET_CATEGORY: {
    code: "PL_TICKET_CATEGORY",
    name: "Helpdesk category",
    seededBy: "config",
    declared: 12,
    openSet: null,
    values: [
      { value: "payroll", label: "Payroll" },
      { value: "attendance", label: "Attendance" },
      { value: "leave", label: "Leave" },
      { value: "documents", label: "Documents" },
      { value: "statutory_pf_esi", label: "Statutory / PF / ESI" },
      { value: "it", label: "IT" },
      { value: "facilities", label: "Facilities" },
      { value: "transport", label: "Transport" },
      { value: "canteen", label: "Canteen" },
      { value: "policy_query", label: "Policy query" },
      { value: "grievance", label: "Grievance" },
      { value: "other", label: "Other" },
    ],
  },
  PL_TICKET_STATUS: {
    code: "PL_TICKET_STATUS",
    name: "Ticket status",
    seededBy: "system",
    declared: 6,
    openSet: null,
    values: [
      { value: "open", label: "Open" },
      { value: "in_progress", label: "In progress" },
      { value: "awaiting_employee", label: "Awaiting employee" },
      { value: "resolved", label: "Resolved" },
      { value: "closed", label: "Closed" },
      { value: "reopened", label: "Reopened" },
    ],
  },
  PL_TIMEZONE: {
    code: "PL_TIMEZONE",
    name: "Time zone",
    seededBy: "system",
    declared: 2,
    openSet: "full IANA tz database seeded at install",
    values: [
      { value: "asia_kolkata", label: "Asia/Kolkata" },
    ],
  },
  PL_UNMATCHED_ACTION: {
    code: "PL_UNMATCHED_ACTION",
    name: "Unmatched record action",
    seededBy: "config",
    declared: 3,
    openSet: null,
    values: [
      { value: "hold", label: "Hold" },
      { value: "create", label: "Create" },
      { value: "reject", label: "Reject" },
    ],
  },
  PL_VARIANCE_ACTION: {
    code: "PL_VARIANCE_ACTION",
    name: "Invoice variance action",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "accept", label: "Accept" },
      { value: "query", label: "Query" },
      { value: "reduce", label: "Reduce" },
    ],
  },
  PL_VERIFICATION_STATUS: {
    code: "PL_VERIFICATION_STATUS",
    name: "Verification status",
    seededBy: "system",
    declared: 3,
    openSet: null,
    values: [
      { value: "pending", label: "Pending" },
      { value: "verified", label: "Verified" },
      { value: "rejected", label: "Rejected" },
    ],
  },
  PL_WAGE_TYPE: {
    code: "PL_WAGE_TYPE",
    name: "Wage type",
    seededBy: "config",
    declared: 6,
    openSet: null,
    values: [
      { value: "monthly", label: "Monthly" },
      { value: "daily", label: "Daily" },
      { value: "hourly", label: "Hourly" },
      { value: "piece_rate", label: "Piece rate" },
      { value: "stipend", label: "Stipend" },
      { value: "retainer", label: "Retainer" },
    ],
  },
  PL_WEEKDAY: {
    code: "PL_WEEKDAY",
    name: "Day of week",
    seededBy: "system",
    declared: 7,
    openSet: null,
    values: [
      { value: "monday", label: "Monday" },
      { value: "tuesday", label: "Tuesday" },
      { value: "wednesday", label: "Wednesday" },
      { value: "thursday", label: "Thursday" },
      { value: "friday", label: "Friday" },
      { value: "saturday", label: "Saturday" },
      { value: "sunday", label: "Sunday" },
    ],
  },
  PL_WORKER_CLASS: {
    code: "PL_WORKER_CLASS",
    name: "Worker class",
    seededBy: "config",
    declared: 9,
    openSet: null,
    values: [
      { value: "staff_monthly", label: "Staff — monthly" },
      { value: "staff_probation", label: "Staff — probation" },
      { value: "workman_permanent", label: "Workman — permanent" },
      { value: "workman_badli_substitute", label: "Workman — badli / substitute" },
      { value: "workman_temporary", label: "Workman — temporary" },
      { value: "contract_labour", label: "Contract labour" },
      { value: "apprentice", label: "Apprentice" },
      { value: "trainee", label: "Trainee" },
      { value: "retainer_consultant", label: "Retainer / consultant" },
    ],
  },
} as const satisfies Record<string, Picklist>;

export type PicklistCode = keyof typeof picklists;

/** The stored values of one picklist, as a literal union. */
export type PicklistValue<C extends PicklistCode> = (typeof picklists)[C]["values"][number]["value"];

/**
 * The stored values of a picklist, shaped for `z.enum(...)` and for select controls.
 *
 * The return type is the literal union, so a zod schema built from it keeps narrow types
 * and a value outside the workbook's set fails to compile. `scripts/generate-workflow-catalog.cjs`
 * recognises this call and records the picklist code on the generated form field, which is
 * how the renderer knows to print the workbook's own labels.
 */
export function picklistValues<C extends PicklistCode>(code: C): [PicklistValue<C>, ...PicklistValue<C>[]] {
  const entries = picklists[code].values;
  return entries.map((entry) => entry.value) as [PicklistValue<C>, ...PicklistValue<C>[]];
}

/** The printable label for a stored value, or the value itself when it is not in the set. */
export function picklistLabel(code: PicklistCode, value: string): string {
  return picklists[code].values.find((entry) => entry.value === value)?.label ?? value;
}

/** True when `value` belongs to the picklist. */
export function isPicklistValue<C extends PicklistCode>(code: C, value: string): value is PicklistValue<C> {
  return picklists[code].values.some((entry) => entry.value === value);
}
