"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Megaphone, RefreshCcw, ShieldOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { apiErrorMessage, getJson, invalidateGetRequests } from "@/lib/client-api";
import { picklists } from "@/lib/picklists";
import { PageIntro, SectionHeading, StatusPill, Surface } from "./page-primitives";
import { ReferencePicker } from "./register-primitives";

type UnknownRecord = Record<string, unknown>;

function asRecord(value: unknown): UnknownRecord {
  return typeof value === "object" && value !== null ? (value as UnknownRecord) : {};
}

function str(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

function int(value: unknown): number {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? Math.trunc(parsed) : 0;
}

function strList(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((entry): entry is string => typeof entry === "string") : [];
}

/** The announcement's real state, as the register derives it. */
function statusTone(state: string): "success" | "warning" | "danger" | "info" | "neutral" {
  if (state === "published") return "success";
  if (state === "scheduled") return "info";
  if (state === "archived") return "warning";
  if (state === "draft") return "neutral";
  return "neutral";
}

function stateLabel(state: string): string {
  if (state === "draft") return "Draft";
  if (state === "scheduled") return "Scheduled";
  if (state === "published") return "Published";
  if (state === "archived") return "Archived";
  return state || "—";
}

function basisLabel(basis: string): string {
  if (basis === "stored") return "from a stored state";
  if (basis === "expiry") return "derived from the expiry date";
  if (basis === "publish_at") return "derived from publish-at";
  return basis || "—";
}

function timestamp(value: string): string {
  if (!value) return "—";
  const parsed = Date.parse(value);
  return Number.isFinite(parsed) ? new Date(parsed).toISOString().replace("T", " ").slice(0, 16) : value;
}

/* ------------------------------------------------------------------ */
/* Payload readers                                                     */
/* ------------------------------------------------------------------ */

type BreakdownRow = { key: string; label: string; count: number };

type AudienceView = {
  rule: string;
  valid: boolean;
  error: string;
  everyone: boolean;
  resolvedCount: number;
  populationCount: number;
  byDepartment: BreakdownRow[];
  byLocation: BreakdownRow[];
};

type AnnouncementRow = {
  id: string;
  title: string;
  body: string;
  kind: string;
  audienceRule: string;
  audience: AudienceView;
  channels: string[];
  channelsRecorded: boolean;
  createdAt: string;
  publishAt: string;
  publishAtSource: string;
  expiresOn: string | null;
  state: string;
  stateBasis: string;
  stateReason: string;
  acknowledgementRequired: boolean | null;
  autoGenerated: boolean;
  occasionKey: string | null;
  acknowledgedVersion: string | null;
  languages: string[];
  feedReactionCount: number;
  feedCommentCount: number;
  auditTrail: Array<{ action: string; reason: string | null; createdAt: string }>;
  canWrite: boolean;
  populationCount: number;
};

type Vocabulary = { code: string; label: string };
type GapRow = { field: string; workbook: string; reason: string };
type MetricRow = { metric: string; reason: string };
type DimensionRow = { key: string; label: string; available: boolean; note: string };

type Contract = {
  persistedFields: string[];
  unpersistedFields: GapRow[];
  unavailableMetrics: MetricRow[];
  delivery: { transmits: boolean; summary: string; detail: string };
  quietHours: { configured: boolean; detail: string };
  publishAtFallback: { source: string; note: string };
  types: Vocabulary[];
  channels: Vocabulary[];
  languages: Vocabulary[];
  audienceDimensions: DimensionRow[];
};

type Preview = {
  audience: AudienceView;
  refusal: string;
  dimensions: { departments: string[]; locations: string[]; designations: string[]; legalEntities: string[] };
  sample: Array<{ id: string; employeeCode: string; name: string; department: string | null; location: string | null }>;
  contract: Contract | null;
};

function readBreakdown(value: unknown): BreakdownRow[] {
  return (Array.isArray(value) ? (value as UnknownRecord[]) : []).map((entry) => ({
    key: str(entry.key, "—"),
    label: str(entry.label, str(entry.key, "—")),
    count: int(entry.count),
  }));
}

function readAudience(value: unknown): AudienceView {
  const record = asRecord(value);
  return {
    rule: str(record.rule),
    valid: record.valid === true,
    error: str(record.error),
    everyone: record.everyone === true,
    resolvedCount: int(record.resolvedCount),
    populationCount: int(record.populationCount),
    byDepartment: readBreakdown(record.byDepartment),
    byLocation: readBreakdown(record.byLocation),
  };
}

function readVocabulary(value: unknown): Vocabulary[] {
  return (Array.isArray(value) ? (value as UnknownRecord[]) : []).map((entry) => ({ code: str(entry.code), label: str(entry.label, str(entry.code)) }));
}

function readContract(value: unknown): Contract | null {
  const record = asRecord(value);
  if (Object.keys(record).length === 0) return null;
  const delivery = asRecord(record.delivery);
  const quietHours = asRecord(record.quietHours);
  const fallback = asRecord(record.publishAtFallback);
  return {
    persistedFields: strList(record.persistedFields),
    unpersistedFields: (Array.isArray(record.unpersistedFields) ? (record.unpersistedFields as UnknownRecord[]) : []).map((entry) => ({
      field: str(entry.field),
      workbook: str(entry.workbook),
      reason: str(entry.reason),
    })),
    unavailableMetrics: (Array.isArray(record.unavailableMetrics) ? (record.unavailableMetrics as UnknownRecord[]) : []).map((entry) => ({
      metric: str(entry.metric),
      reason: str(entry.reason),
    })),
    delivery: { transmits: delivery.transmits === true, summary: str(delivery.summary), detail: str(delivery.detail) },
    quietHours: { configured: quietHours.configured === true, detail: str(quietHours.detail) },
    publishAtFallback: { source: str(fallback.source), note: str(fallback.note) },
    types: readVocabulary(record.types),
    channels: readVocabulary(record.channels),
    languages: readVocabulary(record.languages),
    audienceDimensions: (Array.isArray(record.audienceDimensions) ? (record.audienceDimensions as UnknownRecord[]) : []).map((entry) => ({
      key: str(entry.key),
      label: str(entry.label, str(entry.key)),
      available: entry.available === true,
      note: str(entry.note),
    })),
  };
}

function readRows(payload: unknown): AnnouncementRow[] {
  const data = asRecord(payload).data;
  return (Array.isArray(data) ? (data as UnknownRecord[]) : []).map((item) => ({
    id: str(item.id),
    title: str(item.title, "Untitled announcement"),
    body: str(item.body),
    kind: str(item.kind, "—"),
    audienceRule: str(item.audienceRule, "all"),
    audience: readAudience(item.audience),
    channels: strList(item.channels),
    channelsRecorded: item.channelsRecorded === true,
    createdAt: str(item.createdAt),
    publishAt: str(item.publishAt),
    publishAtSource: str(item.publishAtSource),
    expiresOn: typeof item.expiresOn === "string" ? item.expiresOn : null,
    state: str(item.state, "published"),
    stateBasis: str(item.stateBasis),
    stateReason: str(item.stateReason),
    acknowledgementRequired: typeof item.acknowledgementRequired === "boolean" ? item.acknowledgementRequired : null,
    autoGenerated: item.autoGenerated === true,
    occasionKey: typeof item.occasionKey === "string" ? item.occasionKey : null,
    acknowledgedVersion: typeof item.acknowledgedVersion === "string" ? item.acknowledgedVersion : null,
    languages: strList(item.languages),
    feedReactionCount: int(item.feedReactionCount),
    feedCommentCount: int(item.feedCommentCount),
    auditTrail: (Array.isArray(item.auditTrail) ? (item.auditTrail as UnknownRecord[]) : []).map((entry) => ({
      action: str(entry.action, "—"),
      reason: typeof entry.reason === "string" ? entry.reason : null,
      createdAt: str(entry.createdAt),
    })),
    canWrite: item.canWrite === true,
    populationCount: int(item.populationCount),
  }));
}

function readPreview(payload: unknown): Preview {
  const data = asRecord(asRecord(payload).data);
  const dimensions = asRecord(data.dimensions);
  return {
    audience: readAudience(data),
    refusal: str(data.refusal),
    dimensions: {
      departments: strList(dimensions.departments),
      locations: strList(dimensions.locations),
      designations: strList(dimensions.designations),
      legalEntities: strList(dimensions.legalEntities),
    },
    sample: (Array.isArray(data.sample) ? (data.sample as UnknownRecord[]) : []).map((entry) => ({
      id: str(entry.id),
      employeeCode: str(entry.employeeCode),
      name: str(entry.name),
      department: typeof entry.department === "string" ? entry.department : null,
      location: typeof entry.location === "string" ? entry.location : null,
    })),
    contract: readContract(data.contract),
  };
}

/* ------------------------------------------------------------------ */
/* Compose-side constants that mirror the server module                */
/* ------------------------------------------------------------------ */

/** `publishAnnouncementSchema.kind` — the six values the write path stores. */
const STORED_KINDS = ["management", "project", "star", "joiner", "referral", "birthday"] as const;

const DEFAULT_EXPIRY_DAYS = 30;

function defaultExpiryFromToday(): string {
  return new Date(Date.now() + DEFAULT_EXPIRY_DAYS * 86_400_000).toISOString().slice(0, 10);
}

const ANNOUNCEMENT_CHANNELS = picklists.PL_ANNOUNCEMENT_CHANNEL.values;
const selectClass = "h-10 w-full min-w-0 max-w-full rounded-xl border border-border bg-card px-3 text-xs font-semibold text-foreground";
const inputClass = "h-10 w-full min-w-0 max-w-full rounded-xl border border-border bg-card px-3 text-xs text-foreground";
const textareaClass = "min-h-24 w-full rounded-xl border border-border bg-card px-3 py-2 text-xs text-foreground";

export function AnnouncementsPage() {
  // Deep-link preselect (?record=<announcementId>); lazy initializer keeps SSR output stable.
  const [selectedId, setSelectedId] = useState(() => {
    if (typeof window === "undefined") return "";
    return new URLSearchParams(window.location.search).get("record") ?? "";
  });
  const [rows, setRows] = useState<AnnouncementRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [revision, setRevision] = useState(0);
  const [stateFilter, setStateFilter] = useState("all");
  const [search, setSearch] = useState("");

  // Compose form.
  const [workbookType, setWorkbookType] = useState("general");
  const [storedKind, setStoredKind] = useState<string>("management");
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [rule, setRule] = useState("all");
  const [expiresOn, setExpiresOn] = useState(() => defaultExpiryFromToday());
  const [expiryTouched, setExpiryTouched] = useState(false);
  const [channels, setChannels] = useState<string[]>(["employee_portal", "mobile_push"]);
  const [ackRequired, setAckRequired] = useState(false);
  const [attachmentId, setAttachmentId] = useState("");
  const [preview, setPreview] = useState<Preview | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewError, setPreviewError] = useState("");
  const [publishBusy, setPublishBusy] = useState(false);
  const [publishError, setPublishError] = useState("");
  const [publishNotice, setPublishNotice] = useState("");

  const refresh = useCallback(() => {
    invalidateGetRequests();
    setRevision((n) => n + 1);
  }, []);

  useEffect(() => {
    let live = true;
    void (async () => {
      setLoading(true);
      setError("");
      try {
        const payload = await getJson("/api/v1/announcement-register?view=register&pageSize=100");
        if (live) setRows(readRows(payload));
      } catch (err) {
        if (live) setError(err instanceof Error ? err.message : "The announcement register could not be loaded.");
      } finally {
        if (live) setLoading(false);
      }
    })();
    return () => {
      live = false;
    };
  }, [revision]);

  // Live resolved-audience preview. Debounced so typing a rule does not fan out
  // one query per keystroke; the count itself is never estimated.
  useEffect(() => {
    let live = true;
    const handle = setTimeout(() => {
      void (async () => {
        setPreviewLoading(true);
        setPreviewError("");
        try {
          const payload = await getJson(`/api/v1/announcement-register?view=audience&rule=${encodeURIComponent(rule || "all")}`);
          if (live) setPreview(readPreview(payload));
        } catch (err) {
          if (live) {
            setPreview(null);
            setPreviewError(err instanceof Error ? err.message : "The audience could not be resolved.");
          }
        } finally {
          if (live) setPreviewLoading(false);
        }
      })();
    }, 300);
    return () => {
      live = false;
      clearTimeout(handle);
    };
  }, [rule, revision]);

  const contract = preview?.contract ?? null;

  const filtered = useMemo(() => {
    const needle = search.trim().toLowerCase();
    return rows.filter((row) => {
      if (stateFilter !== "all" && row.state !== stateFilter) return false;
      if (needle && !`${row.title} ${row.audienceRule} ${row.body}`.toLowerCase().includes(needle)) return false;
      return true;
    });
  }, [rows, search, stateFilter]);

  const active = useMemo(() => rows.find((row) => row.id === selectedId) ?? filtered[0] ?? null, [rows, selectedId, filtered]);

  const canWrite = rows.length > 0 ? rows[0]!.canWrite : true;

  /** The refusal the server would raise, stated before the click. */
  const composeRefusal = useMemo(() => {
    if (!canWrite) return "Publishing an announcement needs the employee write permission, which this role does not hold.";
    if (previewLoading) return "Resolving the audience…";
    if (previewError) return `The audience could not be resolved, so the audience is unknown: ${previewError}`;
    if (preview?.refusal) return preview.refusal;
    if (title.trim().length < 5) return "A title of at least 5 characters is required.";
    if (body.trim().length < 20) return "A body of at least 20 characters is required. The write path stores one body and refuses a shorter one.";
    if (channels.length === 0) return "At least one delivery channel must be selected.";
    return "";
  }, [canWrite, previewLoading, previewError, preview, title, body, channels]);

  const quietHoursNote =
    workbookType === "emergency"
      ? "Emergency carries the quiet-hours bypass. It is recorded against this announcement. No quiet-hours window is configured in this system, so the bypass changes nothing today."
      : "This type carries no quiet-hours bypass — and is not being held either. No quiet-hours window is configured in this system, so nothing is deferred and no quiet-hours check has been passed.";

  async function publish(): Promise<void> {
    setPublishBusy(true);
    setPublishError("");
    setPublishNotice("");
    try {
      const payload: UnknownRecord = {
        title: title.trim(),
        body: body.trim(),
        audience: rule.trim() || "all",
        kind: storedKind,
        announcementType: workbookType,
        channels,
        acknowledgementRequired: ackRequired,
      };
      if (expiresOn) payload.expiresAt = expiresOn;
      if (attachmentId.trim()) payload.attachmentDocumentId = attachmentId.trim();
      const response = await fetch("/api/v1/announcements", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(payload),
        cache: "no-store",
      });
      if (!response.ok) {
        const parsed: unknown = await response.json().catch(() => null);
        throw new Error(apiErrorMessage(parsed, response.status, `The announcement could not be published (${response.status}).`));
      }
      setTitle("");
      setBody("");
      setPublishNotice(
        `Published to ${preview?.audience.resolvedCount ?? 0} employee${preview?.audience.resolvedCount === 1 ? "" : "s"}. One announcement row and one audit event were written. Nothing was sent on any channel.`,
      );
      invalidateGetRequests();
      setRevision((n) => n + 1);
    } catch (err) {
      setPublishError(err instanceof Error ? err.message : "The announcement could not be published.");
    } finally {
      setPublishBusy(false);
    }
  }

  return (
    <div className="mx-auto w-full min-w-0 max-w-[1600px]">
      <PageIntro
        eyebrow="EXPERIENCE · SCR-066"
        title="Announcements"
        description="Compose an announcement, resolve its audience against real employee records before it goes out, and read the register by the state each announcement actually derives to."
        action={
          <Button variant="outline" className="h-10 rounded-xl px-4 text-xs font-bold" onClick={refresh}>
            <RefreshCcw className="mr-1.5 size-4" /> Refresh
          </Button>
        }
      />

      <Surface className="mb-6 border-warning/40">
        <SectionHeading
          title="Selecting a channel does not send"
          description={
            contract?.delivery.detail ??
            "No component of this system transmits to email, mobile push, WhatsApp or a notice board. The only notification path writes rows into the in-app notifications table for a person to read when they next open the workspace. External providers must be configured and validated before any external delivery can be claimed."
          }
          action={<StatusPill tone="warning">Records intent, does not transmit</StatusPill>}
        />
        <p className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground">
          <ShieldOff className="mt-0.5 size-3.5 shrink-0 text-warning" />
          On this screen the channel is not even stored: the write endpoint accepts no channel key, so the intended channel is discarded before the record is written. The Channel column reads whatever the record carries and says so when it carries nothing.
        </p>
      </Surface>

      <div className="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border bg-card px-4 py-3">
        <label className="flex w-full min-w-0 items-center gap-2 sm:w-auto">
          <span className="text-xs font-bold text-muted-foreground">State</span>
          <select aria-label="Announcement state filter" className={selectClass} value={stateFilter} onChange={(e) => setStateFilter(e.target.value)}>
            <option value="all">All states</option>
            <option value="draft">Draft</option>
            <option value="scheduled">Scheduled</option>
            <option value="published">Published</option>
            <option value="archived">Archived</option>
          </select>
        </label>
        <input aria-label="Search announcements" className={inputClass} placeholder="Title, audience rule or body" value={search} onChange={(e) => setSearch(e.target.value)} />
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.55fr_1fr]">
        <Surface>
          <SectionHeading
            title="Register"
            description={loading ? "Loading…" : `${filtered.length} announcement${filtered.length === 1 ? "" : "s"} in the current scope`}
          />
          {loading ? (
            <p className="py-6 text-center text-xs text-muted-foreground">Loading…</p>
          ) : error ? (
            <div className="flex flex-col items-center gap-3 py-6 text-center">
              <p className="text-xs leading-relaxed text-muted-foreground">{error}</p>
              <Button variant="outline" size="sm" className="h-10 sm:h-8 rounded-lg text-xs" onClick={refresh}>
                <RefreshCcw className="mr-1.5 size-3.5" /> Retry
              </Button>
            </div>
          ) : filtered.length === 0 ? (
            <p className="py-6 text-center text-xs leading-relaxed text-muted-foreground">
              {rows.length === 0
                ? "No announcements have been published yet. Compose one below; it publishes the moment it is created."
                : "No announcements match these filters."}
            </p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[560px] text-left text-sm">
                <thead>
                  <tr className="text-[11px] uppercase tracking-wider text-muted-foreground">
                    <th className="px-3 py-2 font-bold">Announcement</th>
                    <th className="px-3 py-2 font-bold">Audience</th>
                    <th className="px-3 py-2 font-bold">Channel</th>
                    <th className="px-3 py-2 font-bold">Status</th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((row) => {
                    const selected = row.id === active?.id;
                    return (
                      <tr key={row.id}>
                        <td colSpan={4} className="p-0">
                          <button
                            type="button"
                            onClick={() => setSelectedId(row.id)}
                            aria-current={selected ? "true" : undefined}
                            className={`mb-2 grid w-full grid-cols-[1.6fr_1.2fr_1fr_auto] items-center gap-3 rounded-xl border px-3 py-3 text-left transition-colors ${selected ? "border-primary/50 bg-primary/5" : "border-border/80 bg-card hover:border-primary/40"}`}
                          >
                            <span className="min-w-0 text-xs font-semibold text-foreground">
                              <span className="block truncate">{row.title}</span>
                              <span className="block truncate font-normal text-muted-foreground">{timestamp(row.publishAt)}</span>
                            </span>
                            <span className="min-w-0 text-xs text-muted-foreground">
                              {row.audience.valid ? (
                                <>
                                  <span className="block font-semibold text-foreground">{row.audience.resolvedCount} employee{row.audience.resolvedCount === 1 ? "" : "s"}</span>
                                  <span className="block truncate">{row.audienceRule}</span>
                                </>
                              ) : (
                                <span className="block text-destructive">Rule unresolvable · {row.audienceRule}</span>
                              )}
                            </span>
                            <span className="min-w-0 text-xs text-muted-foreground">
                              {row.channelsRecorded ? row.channels.join(", ") : <span className="italic">Not recorded</span>}
                            </span>
                            <span className="justify-self-end"><StatusPill tone={statusTone(row.state)}>{stateLabel(row.state)}</StatusPill></span>
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </Surface>

        <Surface>
          <SectionHeading
            title="Announcement detail"
            description={active ? active.title : "Select an announcement to inspect it"}
            action={active ? <StatusPill tone={statusTone(active.state)}>{stateLabel(active.state)}</StatusPill> : undefined}
          />
          {!active ? (
            <p className="py-6 text-center text-xs leading-relaxed text-muted-foreground">No announcement selected.</p>
          ) : (
            <div className="space-y-4">
              <p className="whitespace-pre-wrap rounded-xl border border-border/70 bg-secondary/30 px-3 py-2 text-xs leading-relaxed text-foreground">
                {active.body || "No body was stored on this announcement."}
              </p>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">State timeline</h3>
                <dl className="mt-2 space-y-2 text-xs">
                  {[
                    ["Created", timestamp(active.createdAt)],
                    ["Publish at", `${timestamp(active.publishAt)} (${active.publishAtSource})`],
                    ["Expires on", active.expiresOn ?? "No expiry stored"],
                    ["State", `${stateLabel(active.state)} — ${basisLabel(active.stateBasis)}`],
                  ].map(([label, value]) => (
                    <div key={label} className="flex justify-between gap-3 border-b border-border/50 pb-1.5">
                      <dt className="text-muted-foreground">{label}</dt>
                      <dd className="text-right font-semibold text-foreground">{value}</dd>
                    </div>
                  ))}
                </dl>
                <p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">{active.stateReason}</p>
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Audience breakdown</h3>
                {active.audience.valid ? (
                  <>
                    <p className="mt-1 text-xs text-foreground">
                      <span className="font-semibold">{active.audience.resolvedCount}</span> of {active.audience.populationCount} active employees, resolved now from <span className="font-mono">{active.audienceRule}</span>.
                    </p>
                    <div className="mt-2 flex flex-wrap gap-1.5">
                      {active.audience.byDepartment.slice(0, 8).map((entry) => (
                        <span key={`d-${entry.key}`} className="rounded-lg border border-border/70 bg-secondary/40 px-2 py-1 text-[11px] text-foreground">{entry.label} · {entry.count}</span>
                      ))}
                      {active.audience.byLocation.slice(0, 8).map((entry) => (
                        <span key={`l-${entry.key}`} className="rounded-lg border border-border/70 bg-secondary/40 px-2 py-1 text-[11px] text-foreground">{entry.label} · {entry.count}</span>
                      ))}
                    </div>
                  </>
                ) : (
                  <p className="mt-1 text-xs leading-relaxed text-destructive">{active.audience.error}</p>
                )}
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Channels</h3>
                <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
                  {active.channelsRecorded
                    ? `${active.channels.join(", ")} — recorded as intent. Nothing was transmitted on any of them.`
                    : "No channel is recorded on this announcement. The write path stores none, so no channel intent was retained and nothing was transmitted."}
                </p>
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Acknowledgement and reads</h3>
                <ul className="mt-2 space-y-1.5 text-[11px] leading-relaxed text-muted-foreground">
                  <li>
                    <span className="font-semibold text-foreground">Read count:</span> unavailable. No read receipt is recorded against an announcement anywhere in this system, so there is no row to count.
                  </li>
                  <li>
                    <span className="font-semibold text-foreground">Acknowledgement count:</span> unavailable. No table records an acknowledgement of an announcement, and the write path stores no acknowledgement flag.
                  </li>
                  <li>
                    <span className="font-semibold text-foreground">Acknowledged version:</span> unavailable. An announcement carries no version history, so a policy announcement cannot retain the version that was acknowledged.
                  </li>
                  <li>
                    <span className="font-semibold text-foreground">Acknowledgement required:</span>{" "}
                    {active.acknowledgementRequired === null ? "not stored on this record." : active.acknowledgementRequired ? "yes." : "no."}
                  </li>
                  <li>
                    <span className="font-semibold text-foreground">Auto-generated:</span>{" "}
                    {active.autoGenerated
                      ? `yes — raised by the occasion job${active.occasionKey ? ` (${active.occasionKey})` : ""}, not typed by anyone.`
                      : "no. This announcement was published by a person."}
                  </li>
                  <li>
                    <span className="font-semibold text-foreground">Feed reactions / comments:</span> {active.feedReactionCount} / {active.feedCommentCount}. These are real social-feed rows against the same record. They are not reads and not acknowledgements.
                  </li>
                  <li>
                    <span className="font-semibold text-foreground">Language variants:</span>{" "}
                    {active.languages.length > 0 ? active.languages.join(", ") : "none stored. The data model holds one title and one body per announcement."}
                  </li>
                </ul>
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Audit trail</h3>
                {active.auditTrail.length === 0 ? (
                  <p className="mt-1 text-xs text-muted-foreground">No audit event is recorded against this announcement.</p>
                ) : (
                  <ul className="mt-2 space-y-1">
                    {active.auditTrail.map((entry, index) => (
                      <li key={`${entry.action}-${index}`} className="flex justify-between gap-3 rounded-lg border border-border/60 bg-secondary/30 px-2 py-1 text-[11px]">
                        <span className="text-foreground">{entry.action}{entry.reason ? ` · ${entry.reason}` : ""}</span>
                        <span className="shrink-0 tabular-nums text-muted-foreground">{timestamp(entry.createdAt)}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            </div>
          )}
        </Surface>
      </div>

      <Surface className="mt-6">
        <SectionHeading
          title="Compose an announcement"
          description="Creating an announcement publishes it immediately: there is no draft step and no scheduled send. The audience is resolved against live employee records before the write, and a rule that resolves to nobody is refused."
          action={preview && preview.audience.valid ? <StatusPill tone={preview.audience.resolvedCount > 0 ? "success" : "danger"}>{preview.audience.resolvedCount} resolved</StatusPill> : undefined}
        />

        <div className="grid gap-5 lg:grid-cols-[1.3fr_1fr]">
          <div className="space-y-3">
            <div className="grid gap-3 sm:grid-cols-2">
              <label className="flex w-full min-w-0 flex-col gap-1 sm:w-auto">
                <span className="text-[11px] font-bold text-muted-foreground">Announcement type (PL_ANNOUNCEMENT_TYPE)</span>
                <select aria-label="Announcement type" className={selectClass} value={workbookType} onChange={(e) => setWorkbookType(e.target.value)}>
                  {(contract?.types ?? [{ code: "general", label: "General" }, { code: "policy", label: "Policy" }, { code: "emergency", label: "Emergency" }, { code: "celebration", label: "Celebration" }, { code: "statutory_notice", label: "Statutory notice" }]).map((option) => (
                    <option key={option.code} value={option.code}>{option.label}</option>
                  ))}
                </select>
              </label>
              <label className="flex w-full min-w-0 flex-col gap-1 sm:w-auto">
                <span className="text-[11px] font-bold text-muted-foreground">Stored kind — this is what persists</span>
                <select aria-label="Stored kind" className={selectClass} value={storedKind} onChange={(e) => setStoredKind(e.target.value)}>
                  {STORED_KINDS.map((option) => (
                    <option key={option} value={option}>{option}</option>
                  ))}
                </select>
              </label>
            </div>
            <p className="rounded-xl border border-border/70 bg-secondary/30 px-3 py-2 text-[11px] leading-relaxed text-muted-foreground">
              The workbook type is stored on the record alongside the stored kind, which is this system&apos;s own six-value feed taxonomy; the two are kept apart rather than mapped onto one another. {quietHoursNote}
            </p>

            <label className="flex w-full min-w-0 flex-col gap-1 sm:w-auto">
              <span className="text-[11px] font-bold text-muted-foreground">Announcement title</span>
              <input aria-label="Announcement title" className={inputClass} minLength={5} maxLength={120} placeholder="Diwali holiday schedule" value={title} onChange={(e) => setTitle(e.target.value)} />
            </label>

            <label className="flex w-full min-w-0 flex-col gap-1 sm:w-auto">
              <span className="text-[11px] font-bold text-muted-foreground">Body</span>
              <textarea aria-label="Announcement body" className={textareaClass} maxLength={5000} placeholder="Plants close early on…" value={body} onChange={(e) => setBody(e.target.value)} />
            </label>

            <label className="flex w-full min-w-0 flex-col gap-1 sm:w-auto">
              <span className="text-[11px] font-bold text-muted-foreground">Audience rule</span>
              <input
                aria-label="Audience rule"
                className={inputClass}
                maxLength={120}
                placeholder="all  ·  department:Engineering;location:Pune  ·  employee:EMP-001,EMP-002"
                value={rule}
                onChange={(e) => setRule(e.target.value)}
              />
            </label>

            <label className="flex w-full min-w-0 flex-col gap-1 sm:w-auto">
              <span className="text-[11px] font-bold text-muted-foreground">Expires on — defaults to publish + {DEFAULT_EXPIRY_DAYS} days</span>
              <input
                aria-label="Expires on"
                type="date"
                className={inputClass}
                value={expiresOn}
                onChange={(e) => {
                  setExpiryTouched(true);
                  setExpiresOn(e.target.value);
                }}
              />
              {!expiryTouched && <span className="text-[11px] text-muted-foreground">Defaulted to {expiresOn}. Change it to override.</span>}
            </label>

            <fieldset className="flex flex-col gap-1">
              <legend className="text-[11px] font-bold text-muted-foreground">Delivery channels (PL_ANNOUNCEMENT_CHANNEL) — recorded as intent, never transmitted</legend>
              <div className="mt-1 flex flex-wrap gap-3">
                {ANNOUNCEMENT_CHANNELS.map((channel) => (
                  <label key={channel.value} className="flex items-center gap-1.5 text-[11px] text-foreground">
                    <input
                      type="checkbox"
                      checked={channels.includes(channel.value)}
                      onChange={(e) =>
                        setChannels((current) =>
                          e.target.checked ? [...current, channel.value] : current.filter((value) => value !== channel.value),
                        )
                      }
                    />
                    {channel.label}
                  </label>
                ))}
              </div>
            </fieldset>

            <label className="flex items-center gap-2 text-[11px] font-bold text-muted-foreground">
              <input type="checkbox" checked={ackRequired} onChange={(e) => setAckRequired(e.target.checked)} />
              Acknowledgement required
            </label>

            <label className="flex flex-col gap-1">
              <span className="text-[11px] font-bold text-muted-foreground">Attachment document id (optional)</span>
              <ReferencePicker
                endpoint="/api/v1/documents"
                ariaLabel="Attachment document"
                className={inputClass}
                placeholder="Search an already-uploaded document…"
                value={attachmentId}
                onChange={setAttachmentId}
              />
            </label>

            {publishError ? <p role="alert" className="text-xs text-destructive">{publishError}</p> : null}
            {publishNotice ? <p className="rounded-xl border border-success/30 bg-success/5 px-3 py-2 text-xs leading-relaxed text-foreground">{publishNotice}</p> : null}

            <div className="flex flex-wrap items-center gap-2">
              <Button
                size="sm"
                className="h-10 sm:h-9 rounded-lg text-xs"
                disabled={publishBusy || composeRefusal !== ""}
                title={composeRefusal || undefined}
                onClick={() => void publish()}
              >
                {publishBusy ? "Publishing…" : "Create and publish announcement"}
              </Button>
              <Button size="sm" variant="outline" className="h-10 sm:h-9 rounded-lg text-xs" disabled title="There is no schedule write. The write endpoint accepts no publish-at, so a future publish time cannot be stored and nothing would fire at it.">
                Schedule
              </Button>
              <Button size="sm" variant="outline" className="h-10 sm:h-9 rounded-lg text-xs" disabled title="Archiving is not a write. An announcement archives itself when its stored expiry date passes; there is no endpoint that archives one early and no state column to set.">
                Archive
              </Button>
            </div>
            <ul className="space-y-1 text-[11px] leading-relaxed text-muted-foreground">
              {composeRefusal ? (
                <li className="flex items-start gap-1.5 text-destructive">
                  <AlertTriangle className="mt-0.5 size-3 shrink-0" /> Create and publish is disabled: {composeRefusal}
                </li>
              ) : (
                <li className="flex items-start gap-1.5">
                  <Megaphone className="mt-0.5 size-3 shrink-0" /> Create and publish writes one announcement row and one audit event, addressed to {preview?.audience.resolvedCount ?? 0} employees. It sends nothing.
                </li>
              )}
              <li>Schedule is disabled: the write endpoint accepts no publish-at, so a future publish time cannot be stored and nothing would fire at it.</li>
              <li>Archive is disabled: an announcement archives itself when its stored expiry date passes. No endpoint archives one early and there is no state column to set.</li>
            </ul>
          </div>

          <div className="space-y-3">
            <div className="rounded-xl border border-border/80 bg-card p-4">
              <p className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground">Resolved audience</p>
              {previewLoading ? (
                <p className="mt-2 text-xs text-muted-foreground">Resolving…</p>
              ) : previewError ? (
                <p className="mt-2 text-xs leading-relaxed text-destructive">{previewError}</p>
              ) : !preview ? (
                <p className="mt-2 text-xs text-muted-foreground">No resolution yet.</p>
              ) : !preview.audience.valid ? (
                <p className="mt-2 text-xs leading-relaxed text-destructive">{preview.audience.error}</p>
              ) : (
                <>
                  <p className="mt-2 font-mono text-[26px] font-bold leading-8 text-foreground tabular-nums">{preview.audience.resolvedCount}</p>
                  <p className="text-[11px] leading-relaxed text-muted-foreground">
                    of {preview.audience.populationCount} active employees, counted from real employee records — not an estimate.
                  </p>
                  {preview.refusal ? <p className="mt-2 text-xs leading-relaxed text-destructive">{preview.refusal}</p> : null}
                  <div className="mt-3 flex flex-wrap gap-1.5">
                    {preview.audience.byDepartment.slice(0, 6).map((entry) => (
                      <span key={`pd-${entry.key}`} className="rounded-lg border border-border/70 bg-secondary/40 px-2 py-1 text-[11px] text-foreground">{entry.label} · {entry.count}</span>
                    ))}
                  </div>
                  {preview.sample.length > 0 ? (
                    <p className="mt-3 text-[11px] leading-relaxed text-muted-foreground">
                      First few: {preview.sample.slice(0, 5).map((person) => person.name).join(", ")}
                      {preview.audience.resolvedCount > 5 ? ` and ${preview.audience.resolvedCount - 5} more.` : "."}
                    </p>
                  ) : null}
                </>
              )}
            </div>

            <div className="rounded-xl border border-border/80 bg-card p-4">
              <p className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground">Audience dimensions</p>
              <ul className="mt-2 space-y-1 text-[11px] leading-relaxed text-muted-foreground">
                {(contract?.audienceDimensions ?? []).map((dimension) => (
                  <li key={dimension.key}>
                    <span className={dimension.available ? "font-semibold text-foreground" : "font-semibold text-muted-foreground line-through"}>{dimension.key}</span>
                    {" — "}
                    {dimension.note}
                  </li>
                ))}
                {(contract?.audienceDimensions ?? []).length === 0 ? <li>Load the audience preview to list the dimensions.</li> : null}
              </ul>
              {preview ? (
                <p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">
                  Values available now — departments: {preview.dimensions.departments.slice(0, 6).join(", ") || "none"}; locations: {preview.dimensions.locations.slice(0, 6).join(", ") || "none"}.
                </p>
              ) : null}
            </div>
          </div>
        </div>
      </Surface>

      <Surface className="mt-6 border-destructive/40">
        <SectionHeading
          title="Form fields this system cannot store"
          description="Every field below is on FRM-EXP-03 and has nowhere to go. The write endpoint's schema strips any key it does not name, so sending these is a silent no-op. They are listed instead of rendered as inputs, so no process is built on a field that is dropped in transit."
          action={<StatusPill tone="danger">{(contract?.unpersistedFields ?? []).length || 5} gaps</StatusPill>}
        />
        <div className="overflow-x-auto">
          <table className="w-full min-w-[560px] text-left text-sm">
            <thead>
              <tr className="text-[11px] uppercase tracking-wider text-muted-foreground">
                <th className="px-3 py-2 font-bold">Field</th>
                <th className="px-3 py-2 font-bold">Workbook</th>
                <th className="px-3 py-2 font-bold">Why it is not stored</th>
              </tr>
            </thead>
            <tbody>
              {(contract?.unpersistedFields ?? []).map((gap) => (
                <tr key={gap.field} className="border-t border-border/60 align-top">
                  <td className="px-3 py-2 text-xs font-semibold text-foreground">{gap.field}</td>
                  <td className="px-3 py-2 text-xs text-muted-foreground">{gap.workbook}</td>
                  <td className="px-3 py-2 text-xs leading-relaxed text-muted-foreground">{gap.reason}</td>
                </tr>
              ))}
              {(contract?.unpersistedFields ?? []).length === 0 ? (
                <tr className="border-t border-border/60">
                  <td colSpan={3} className="px-3 py-3 text-xs leading-relaxed text-muted-foreground">
                    The audience preview has not loaded, so the stored-field contract is unavailable. Nothing here is being hidden — retry above.
                  </td>
                </tr>
              ) : null}
            </tbody>
          </table>
        </div>
        <p className="mt-4 text-[11px] leading-relaxed text-muted-foreground">
          The channel vocabulary (PL_ANNOUNCEMENT_CHANNEL) is {(contract?.channels ?? []).map((channel) => channel.label).join(", ") || "employee portal, mobile push, email, WhatsApp, notice board display"} and multiple channels are permitted; the language vocabulary (PL_LANGUAGE) carries {(contract?.languages ?? []).length || 14} values. Both come from the picklist registry in `src/lib/picklists.ts`, and both are stored on the announcement. What is still missing is a transport that acts on a channel and a translation path that renders a variant.
        </p>
        <p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">
          {contract?.quietHours.detail ??
            "No quiet-hours window is defined in this system. There is no tenant setting, no table and no constant that states one, and the workbook does not supply the hours. Until a window is configured, no announcement is held back by quiet hours — including the ones that would be."}
        </p>
        <p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">
          {contract?.publishAtFallback.note ??
            "No publish-at is stored. feed_posts.created_at stands in for it, and created_at is never in the future, so Scheduled cannot occur on any existing record."}
        </p>
      </Surface>
    </div>
  );
}
