import {
  Archive,
  Award,
  ArrowLeftRight,
  Banknote,
  BookOpen,
  Briefcase,
  Building2,
  Calculator,
  CalendarCheck,
  CalendarCheck2,
  CalendarDays,
  ChartNoAxesCombined,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  Contact,
  Megaphone,
  UserPlus,
  DoorOpen,
  FileBadge,
  FileCheck,
  FileText,
  Fingerprint,
  Gauge,
  Gem,
  GraduationCap,
  HandCoins,
  HeartHandshake,
  History,
  Home,
  IdCard,
  Inbox,
  IndianRupee,
  KeyRound,
  Landmark,
  LayoutDashboard,
  ListChecks,
  MapPin,
  Mic,
  Network,
  NotebookPen,
  PlugZap,
  Radar,
  Receipt,
  RefreshCw,
  Route,
  Scale,
  ScrollText,
  Settings2,
  ShieldCheck,
  Sparkles,
  Stamp,
  Target,
  Timer,
  TriangleAlert,
  UserCheck,
  UserRoundSearch,
  Users,
  UsersRound,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const navigationIconMap: Record<string, LucideIcon> = {
  archive: Archive,
  "arrow-left-right": ArrowLeftRight,
  banknote: Banknote,
  "book-open": BookOpen,
  briefcase: Briefcase,
  "building-2": Building2,
  calculator: Calculator,
  "calendar-check": CalendarCheck,
  "calendar-check2": CalendarCheck2,
  "calendar-days": CalendarDays,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "circle-check": CircleCheck,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  award: Award,
  megaphone: Megaphone,
  "user-plus": UserPlus,
  "clock-3": Clock3,
  contact: Contact,
  "door-open": DoorOpen,
  "file-badge": FileBadge,
  "file-check": FileCheck,
  "file-text": FileText,
  fingerprint: Fingerprint,
  gauge: Gauge,
  gem: Gem,
  "graduation-cap": GraduationCap,
  "hand-coins": HandCoins,
  "heart-handshake": HeartHandshake,
  history: History,
  home: Home,
  "id-card": IdCard,
  inbox: Inbox,
  "indian-rupee": IndianRupee,
  "key-round": KeyRound,
  landmark: Landmark,
  "layout-dashboard": LayoutDashboard,
  "list-checks": ListChecks,
  "map-pin": MapPin,
  mic: Mic,
  network: Network,
  "notebook-pen": NotebookPen,
  "plug-zap": PlugZap,
  radar: Radar,
  receipt: Receipt,
  "refresh-cw": RefreshCw,
  route: Route,
  scale: Scale,
  "scroll-text": ScrollText,
  "settings-2": Settings2,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  stamp: Stamp,
  target: Target,
  timer: Timer,
  "triangle-alert": TriangleAlert,
  "user-check": UserCheck,
  "user-round-search": UserRoundSearch,
  users: Users,
  "users-round": UsersRound,
  wallet: Wallet,
};

export function getNavigationIcon(name: string) {
  return navigationIconMap[name] ?? LayoutDashboard;
}
