import "server-only";

import { z } from "zod";
import { sqlClient } from "@/lib/db";
import { picklistValues } from "@/lib/picklists";
import { ensureComponent, ensurePayrollScaffold } from "@/server/payroll/service";
import { enforce, tenantTx, uuidOrNull, type Access } from "@/server/platform/access";
import { HttpError } from "@/server/platform/http";
import {
  REFERRAL_MILESTONE_KEYS,
  parseReferralAwardScheme,
  type ReferralAwardScheme,
} from "@/server/talent/pipeline";

export const MIN_ANONYMITY_COHORT = 5;

async function assertEmployee(access: Access, employeeId: string): Promise<void> {
  const [rows] = await tenantTx(access, [
    sqlClient`select 1 from employees where tenant_id = ${access.tenantId} and id = ${employeeId} limit 1`,
  ]);
  if ((rows as unknown[]).length === 0) {
    throw new HttpError({ status: 404, code: "NOT_FOUND", message: "The requested record was not found." });
  }
}

/**
 * EXP-03. `audience` is the workbook's `audience_rule` under the name the feed already used;
 * the resolved audience count and the read and acknowledgement counts are derived, and
 * `@/server/engagement/announcement-register` reports which of them this topology can produce.
 *
 * The vocabularies come from the picklist registry rather than being retyped, so a channel or a
 * type the workbook does not list cannot be stored.
 */
export const publishAnnouncementSchema = z.object({
  title: z.string().trim().min(5).max(120),
  body: z.string().trim().min(20).max(5000),
  audience: z.string().trim().min(1).max(120).default("all"),
  attachmentDocumentId: z.string().uuid().optional(),
  expiresAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  kind: z.enum(["birthday", "joiner", "star", "referral", "project", "management"]).default("management"),
  /** PL_ANNOUNCEMENT_TYPE. Distinct from `kind`, which is this system's own feed taxonomy. */
  announcementType: z.enum(picklistValues("PL_ANNOUNCEMENT_TYPE")).default("general"),
  /** PL_ANNOUNCEMENT_CHANNEL. Records the intended channels; nothing transmits on them. */
  channels: z.array(z.enum(picklistValues("PL_ANNOUNCEMENT_CHANNEL"))).min(1).max(5).default(["employee_portal", "mobile_push"]),
  publishAt: z.string().datetime().optional(),
  acknowledgementRequired: z.boolean().default(false),
  /** PL_LANGUAGE variants, keyed by language code. */
  languageVariants: z.record(z.string().min(2).max(20), z.object({ title: z.string().trim().min(1).max(200), body: z.string().trim().min(1).max(5000) })).optional(),
}).superRefine((value, context) => {
  if (value.expiresAt && value.publishAt && value.expiresAt < value.publishAt.slice(0, 10)) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["expiresAt"], message: "An announcement cannot expire before it publishes." });
  }
});

/**
 * How the announcement came to exist (FRM-EXP-03 `is_auto_generated`, default N).
 *
 * This is NOT on `publishAnnouncementSchema` and is deliberately not accepted from a
 * request body: the flag's only job is to distinguish an announcement the system
 * raised from the employee record from one a person typed, and a caller able to set
 * it could make a typed announcement claim to be automatic. The one writer that
 * passes it is the `engagement.announce_occasions` job. `occasionKey` is what makes
 * that job idempotent - see `@/server/engagement/occasion-announcements`.
 */
export type AnnouncementOrigin = { autoGenerated: boolean; occasionKey: string | null };

const TYPED_BY_A_PERSON: AnnouncementOrigin = { autoGenerated: false, occasionKey: null };

export async function publishAnnouncement(
  access: Access,
  input: z.infer<typeof publishAnnouncementSchema>,
  requestId: string,
  origin: AnnouncementOrigin = TYPED_BY_A_PERSON,
) {
  enforce(access.context, "employee.write", { tenantId: access.tenantId });
  const now = new Date();
  // The workbook defaults publish-at to now and forbids the past; an emergency notice is the
  // one type it exempts from the quiet-hours rule, so scheduling is never forced on it.
  const publishAt = input.publishAt ?? now.toISOString();
  // Compared by day: a client clock a few seconds behind the server is not a scheduling error.
  if (publishAt.slice(0, 10) < now.toISOString().slice(0, 10)) {
    throw new HttpError({ status: 422, code: "POLICY_VIOLATION", message: "An announcement cannot be scheduled into the past." });
  }
  const id = crypto.randomUUID();
  await tenantTx(access, [
    sqlClient`
      insert into feed_posts (id, tenant_id, attributes)
      values (${id}, ${access.tenantId},
        ${JSON.stringify({
          title: input.title,
          body: input.body,
          audience: input.audience,
          attachment_document_id: input.attachmentDocumentId ?? null,
          expires_at: input.expiresAt ?? null,
          kind: input.kind,
          published_by: access.context.actorUserId,
          announcement_type: input.announcementType,
          channels: input.channels,
          publish_at: publishAt,
          acknowledgement_required: input.acknowledgementRequired,
          language_variants: input.languageVariants ?? null,
          // A policy announcement must retain the version that was acknowledged, so
          // the published text is stamped at publish time rather than read live.
          published_version: 1,
          is_auto_generated: origin.autoGenerated,
          auto_occasion_key: origin.occasionKey,
        })}::jsonb)
    `,
    sqlClient`
      insert into audit_events (tenant_id, actor_user_id, membership_id, action, entity_type, entity_id, reason, request_id)
      values (${access.tenantId}, ${access.context.actorUserId}, ${access.context.membershipId},
        'engage.announce', 'feed_post', ${id},
        ${origin.autoGenerated ? `Announcement raised automatically (${origin.occasionKey ?? "no occasion key"})` : "Announcement published"},
        ${uuidOrNull(requestId)}::uuid)
    `,
  ]);
  return { id };
}

export async function listAnnouncements(access: Access, audience: string | null) {
  enforce(access.context, "employee.read", { tenantId: access.tenantId });
  const today = new Date().toISOString().slice(0, 10);
  const filter = audience;
  const [rows] = await tenantTx(access, [
    sqlClient`
      select id, attributes, created_at from feed_posts where tenant_id = ${access.tenantId}
        and (attributes->>'expires_at' is null or attributes->>'expires_at' >= ${today})
        and (${filter}::text is null or attributes->>'audience' in (${audience ?? "all"}, 'all'))
      order by created_at desc limit 50
    `,
  ]);
  return rows;
}

async function ensureRecognitionProgram(access: Access, code = "STAR-MONTHLY"): Promise<string> {
  const [rows] = await tenantTx(access, [
    sqlClient`select id from recognition_programs where tenant_id = ${access.tenantId} and attributes->>'code' = ${code} limit 1`,
  ]);
  const existing = (rows as Array<{ id: string }>)[0];
  if (existing) return existing.id;
  const id = crypto.randomUUID();
  await tenantTx(access, [
    sqlClient`insert into recognition_programs (id, tenant_id, attributes) values (${id}, ${access.tenantId}, ${JSON.stringify({ code, name: "Star of the month" })}::jsonb)`,
  ]);
  return id;
}

export const recognizeSchema = z.object({
  recipientEmployeeId: z.string().uuid(),
  message: z.string().trim().min(1).max(1000),
  points: z.number().int().min(0).max(10000).default(100),
});

export async function recognizeEmployee(access: Access, input: z.infer<typeof recognizeSchema>, requestId: string) {
  enforce(access.context, "employee.write", { tenantId: access.tenantId });
  await assertEmployee(access, input.recipientEmployeeId);
  const [memberRows] = await tenantTx(access, [
    sqlClient`select employee_id from memberships where tenant_id = ${access.tenantId} and user_id = ${access.context.actorUserId} and status = 'active' limit 1`,
  ]);
  const nominator = (memberRows as Array<{ employee_id: string | null }>)[0]?.employee_id ?? null;
  const programId = await ensureRecognitionProgram(access);
  const id = crypto.randomUUID();
  await tenantTx(access, [
    sqlClient`
      insert into recognition_events (id, tenant_id, nominator_employee_id, recipient_employee_id, recognition_program_id, attributes)
      values (${id}, ${access.tenantId}, ${nominator}, ${input.recipientEmployeeId}, ${programId},
        ${JSON.stringify({ message: input.message, points: input.points })}::jsonb)
    `,
    sqlClient`
      insert into audit_events (tenant_id, actor_user_id, membership_id, action, entity_type, entity_id, reason, request_id)
      values (${access.tenantId}, ${access.context.actorUserId}, ${access.context.membershipId},
        'engage.recognize', 'recognition_event', ${id}, 'Recognition recorded', ${uuidOrNull(requestId)}::uuid)
    `,
  ]);
  return { id };
}

/**
 * TAL-05. The candidate's name, mobile, email and resume are not re-keyed here: they live on
 * the candidate record this points at, which is also where the workbook's duplicate check runs.
 * The award scheme, amount, split and maturity are derived - `@/server/engagement/referral-tracking`
 * reads them from the configured scheme and states the gap when a tenant has configured none.
 */
export const referCandidateSchema = z.object({
  requisitionId: z.string().uuid(),
  candidateId: z.string().uuid(),
  applicationId: z.string().uuid().optional(),
  relationship: z.enum(picklistValues("PL_REFERRAL_RELATION")),
  note: z.string().trim().max(500).optional(),
});

export async function referCandidate(access: Access, input: z.infer<typeof referCandidateSchema>) {
  enforce(access.context, "employee.write", { tenantId: access.tenantId });
  const [memberRows] = await tenantTx(access, [
    sqlClient`select employee_id from memberships where tenant_id = ${access.tenantId} and user_id = ${access.context.actorUserId} and status = 'active' limit 1`,
  ]);
  const referrer = (memberRows as Array<{ employee_id: string | null }>)[0]?.employee_id;
  if (!referrer) throw new HttpError({ status: 403, code: "FORBIDDEN", message: "Referrals require a linked employee profile." });
  // The requisition must be open: a referral against a closed or draft opening earns nothing.
  const [requisitionRows] = await tenantTx(access, [
    sqlClient`select attributes->>'status' as status from requisitions where tenant_id = ${access.tenantId} and id = ${input.requisitionId} limit 1`,
  ]);
  const requisitionStatus = (requisitionRows as Array<{ status: string | null }>)[0]?.status ?? null;
  if (requisitionStatus === null) {
    throw new HttpError({ status: 404, code: "NOT_FOUND", message: "The requested record was not found." });
  }
  if (requisitionStatus !== "approved") {
    throw new HttpError({ status: 409, code: "VERSION_CONFLICT", message: `Referrals need an open requisition; this one is ${requisitionStatus}.` });
  }
  const id = crypto.randomUUID();
  await tenantTx(access, [
    sqlClient`
      insert into referrals (id, tenant_id, application_id, candidate_id, referrer_employee_id, attributes)
      values (${id}, ${access.tenantId}, ${input.applicationId ?? null}, ${input.candidateId}, ${referrer},
        ${JSON.stringify({
          requisition_id: input.requisitionId,
          relationship: input.relationship,
          note: input.note ?? null,
          status: "referred",
        })}::jsonb)
    `,
  ]);
  return { id, status: "referred" };
}

/**
 * TAL-05 / R-20. One leg of a referral award.
 *
 * `requiredDays` is deliberately NOT accepted from the caller any more: a tenure
 * threshold supplied with the request is a policy figure typed in at the point of
 * payment. The joining leg is earned by joining, so its threshold is zero; the
 * confirmation leg's threshold is `confirmationTenureDays` on the configured scheme.
 */
export const awardReferralSchema = z.object({
  milestone: z.enum(REFERRAL_MILESTONE_KEYS).default("joining"),
  /** Completed tenure in days, as evidenced by the caller from the joining date. */
  tenureDays: z.number().int().min(0),
  /** The payroll period the award should be paid in. Defaults to the current month. */
  period: z.string().regex(/^\d{4}-\d{2}$/).optional(),
});

export type AwardReferralInput = z.infer<typeof awardReferralSchema>;

/**
 * The award amount is CONFIGURATION AND IS NOT SUPPLIED.
 *
 * Neither workbook states the bounty, the joining/confirmation split or the
 * confirmation tenure; the configuration register marks the award amount
 * configurable and leaves its value blank. There is no scheme master table, so the
 * only place it can live is tenant settings. Reading it when it is absent throws,
 * the way `requireRule` does in `@/server/payroll/rule-pack`, rather than paying a
 * guessed figure into somebody's salary.
 */
export const REFERRAL_AWARD_SCHEME_PATH = "tenant_settings.settings -> 'referral_award_scheme'";

async function requireReferralAwardScheme(access: Access): Promise<ReferralAwardScheme> {
  const [rows] = await tenantTx(access, [
    sqlClient`select settings from tenant_settings where tenant_id = ${access.tenantId} limit 1`,
  ]);
  const settings = ((rows as Array<{ settings: unknown }>)[0]?.settings ?? {}) as Record<string, unknown>;
  const scheme = parseReferralAwardScheme(settings.referral_award_scheme);
  if (!scheme) {
    throw new HttpError({
      status: 422,
      code: "REFERRAL_SCHEME_INCOMPLETE",
      message: `No referral award scheme is configured for this tenant, so the award amount is unknown. Set ${REFERRAL_AWARD_SCHEME_PATH} with a code, currency, joiningAmountMinor, confirmationAmountMinor and confirmationTenureDays before any referral award can be paid.`,
      details: [{ field: "referralAwardScheme", issue: `Not configured at ${REFERRAL_AWARD_SCHEME_PATH}.` }],
    });
  }
  return scheme;
}

/**
 * Pay one leg of a referral award.
 *
 * The payout reaches payroll as an input, not as a manual entry: a `payroll_inputs`
 * row on the `referral_award` component for the referrer, in an open pay period, and
 * `referral_awards.payroll_input_id` pointing back at it. The referral's own
 * requisition carries the position code through to the award, so the register can
 * report which opening the payout was earned against.
 */
export async function awardReferral(access: Access, referralId: string, input: AwardReferralInput, requestId: string) {
  enforce(access.context, "employee.write", { tenantId: access.tenantId });
  const scheme = await requireReferralAwardScheme(access);
  const requiredDays = input.milestone === "confirmation" ? scheme.confirmationTenureDays : 0;
  if (input.tenureDays < requiredDays) {
    throw new HttpError({
      status: 409,
      code: "VERSION_CONFLICT",
      message: `The ${input.milestone} leg needs ${requiredDays} days of tenure; ${input.tenureDays} are completed.`,
    });
  }
  const [rows, awardRows] = await tenantTx(access, [
    sqlClient`
      select r.id, r.attributes, r.referrer_employee_id,
        pos.attributes->>'code' as position_code,
        req.attributes->>'code' as requisition_code,
        -- Names for the announcement. Both are optional: the feed copy falls back rather
        -- than refusing an award because a display name is missing.
        nullif(trim(coalesce(ref.first_name, '') || ' ' || coalesce(ref.last_name, '')), '') as referrer_name,
        nullif(trim(coalesce(cand.attributes->>'name', '')), '') as candidate_name
      from referrals r
      left join employees ref on ref.tenant_id = r.tenant_id and ref.id = r.referrer_employee_id
      left join candidates cand on cand.tenant_id = r.tenant_id and cand.id = r.candidate_id
      left join requisitions req on req.tenant_id = r.tenant_id
        -- Guarded rather than cast blindly: a malformed stored id must read as "no
        -- requisition", not blow up the award with a cast error.
        and req.id = case when r.attributes->>'requisition_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
          then (r.attributes->>'requisition_id')::uuid end
      left join positions pos on pos.tenant_id = req.tenant_id and pos.id = req.position_id
      where r.tenant_id = ${access.tenantId} and r.id = ${referralId} limit 1
    `,
    sqlClient`select attributes->>'milestone' as milestone from referral_awards
      where tenant_id = ${access.tenantId} and referral_id = ${referralId}`,
  ]);
  const referral = (rows as Array<{
    id: string; attributes: { status?: string }; referrer_employee_id: string | null;
    position_code: string | null; requisition_code: string | null;
    referrer_name: string | null; candidate_name: string | null;
  }>)[0];
  if (!referral) throw new HttpError({ status: 404, code: "NOT_FOUND", message: "The requested record was not found." });
  if (!referral.referrer_employee_id) {
    throw new HttpError({ status: 409, code: "VERSION_CONFLICT", message: "This referral names no referring employee, so there is nobody to pay." });
  }
  // The double-payment refusal is now per leg. An award row with no milestone key
  // predates the split and is read as the joining leg, exactly as the register reads it.
  const paid = new Set((awardRows as Array<{ milestone: string | null }>).map((row) => row.milestone ?? "joining"));
  if (paid.has(input.milestone)) {
    throw new HttpError({ status: 409, code: "VERSION_CONFLICT", message: `The ${input.milestone} leg of this referral award was already processed.` });
  }

  const amountMinor = input.milestone === "confirmation" ? scheme.confirmationAmountMinor : scheme.joiningAmountMinor;
  const period = input.period ?? new Date().toISOString().slice(0, 7);
  const scaffold = await ensurePayrollScaffold(access, period);
  const componentId = await ensureComponent(access, "referral_award", "earning");
  const payrollInputId = crypto.randomUUID();
  const awardId = crypto.randomUUID();
  const bothLegsPaid = paid.size + 1 >= REFERRAL_MILESTONE_KEYS.length;
  await tenantTx(access, [
    sqlClient`
      insert into payroll_inputs (id, tenant_id, employee_id, pay_component_id, pay_period_id, attributes)
      values (${payrollInputId}, ${access.tenantId}, ${referral.referrer_employee_id}, ${componentId}, ${scaffold.payPeriodId},
        ${JSON.stringify({
          amount_minor: amountMinor,
          currency: scheme.currency,
          component: "referral_award",
          referral_id: referralId,
          milestone: input.milestone,
          scheme_code: scheme.code,
          position_code: referral.position_code,
        })}::jsonb)
    `,
    sqlClient`
      update referrals set attributes = attributes || ${JSON.stringify({ status: bothLegsPaid ? "awarded" : "part_awarded" })}::jsonb
      where id = ${referralId} and tenant_id = ${access.tenantId}
    `,
    sqlClient`
      insert into referral_awards (id, tenant_id, referral_id, payroll_input_id, pay_component_id, attributes)
      values (${awardId}, ${access.tenantId}, ${referralId}, ${payrollInputId}, ${componentId},
        ${JSON.stringify({
          milestone: input.milestone,
          tenure_days: input.tenureDays,
          required_days: requiredDays,
          amount_minor: amountMinor,
          currency: scheme.currency,
          scheme_code: scheme.code,
          position_code: referral.position_code,
          requisition_code: referral.requisition_code,
          pay_period: period,
          status: "payable",
        })}::jsonb)
    `,
    sqlClient`
      insert into audit_events (tenant_id, actor_user_id, membership_id, action, entity_type, entity_id, reason, request_id)
      values (${access.tenantId}, ${access.context.actorUserId}, ${access.context.membershipId},
        'engage.referral_award', 'referral_award', ${awardId},
        ${`Referral ${input.milestone} leg raised as a payroll input for ${period}`}, ${uuidOrNull(requestId)}::uuid)
    `,
  ]);
  // R-21 names referral among the announcement triggers, alongside birthday, new joiner
  // and star. The other three raise themselves; this one never did, so a referral that
  // reached payroll was invisible on the feed. Raised once per referral per milestone —
  // the occasion key is what stops the second leg re-announcing the first.
  //
  // The amount is deliberately not published: the award is the referrer's pay, and the
  // feed is read by everyone. The announcement says who referred whom, not what they were
  // paid. A failure here must not unmake an award that is already a payroll input, so it
  // is recorded and swallowed rather than allowed to roll the transaction back.
  try {
    await publishAnnouncement(
      access,
      {
        title: `Referral success: ${referral.candidate_name ?? "a new joiner"}`,
        body: `${referral.referrer_name ?? "A colleague"} referred ${referral.candidate_name ?? "a candidate"}`
          + `${referral.position_code ? ` for position ${referral.position_code}` : ""}`
          + `, and the ${input.milestone} milestone has now been reached. Thank you for helping us hire well.`,
        audience: "all",
        kind: "referral",
        announcementType: "general",
        channels: ["employee_portal"],
        acknowledgementRequired: false,
      },
      requestId,
      { autoGenerated: true, occasionKey: `referral:${referralId}:${input.milestone}` },
    );
  } catch (error) {
    await recordAnnouncementFailure(access, awardId, error, requestId);
  }

  return {
    awardId,
    status: "payable",
    milestone: input.milestone,
    amountMinor,
    currency: scheme.currency,
    payrollInputId,
    payPeriod: period,
    positionCode: referral.position_code,
  };
}

/**
 * The announcement failed but the award stands. Recorded against the award so the omission
 * is visible, rather than logged where nobody looks or swallowed silently.
 */
async function recordAnnouncementFailure(access: Access, awardId: string, error: unknown, requestId: string): Promise<void> {
  const message = error instanceof Error ? error.message : "The referral announcement could not be published.";
  await tenantTx(access, [
    sqlClient`
      insert into audit_events (tenant_id, actor_user_id, membership_id, action, entity_type, entity_id, reason, request_id)
      values (${access.tenantId}, ${access.context.actorUserId}, ${access.context.membershipId},
        'engage.referral_announcement_failed', 'referral_award', ${awardId},
        ${`The award was raised; its announcement was not published: ${message}`}, ${uuidOrNull(requestId)}::uuid)
    `,
  ]);
}

export const createSurveySchema = z.object({
  code: z.string().trim().min(1).max(40),
  title: z.string().trim().min(1).max(200),
  questions: z.array(z.object({ key: z.string().min(1).max(40), text: z.string().min(1).max(500), scale: z.number().int().min(2).max(10).default(5) })).min(1).max(30),
});

export async function createSurvey(access: Access, input: z.infer<typeof createSurveySchema>) {
  enforce(access.context, "employee.write", { tenantId: access.tenantId });
  const id = crypto.randomUUID();
  await tenantTx(access, [
    sqlClient`
      insert into surveys (id, tenant_id, attributes)
      values (${id}, ${access.tenantId}, ${JSON.stringify({ code: input.code, title: input.title, questions: input.questions })}::jsonb)
    `,
  ]);
  return { id };
}

export async function startSurveyRun(access: Access, surveyId: string, audience: string | null) {
  enforce(access.context, "employee.write", { tenantId: access.tenantId });
  const id = crypto.randomUUID();
  await tenantTx(access, [
    sqlClient`
      insert into survey_runs (id, tenant_id, survey_id, attributes)
      values (${id}, ${access.tenantId}, ${surveyId}, ${JSON.stringify({ audience: audience ?? "all", status: "open" })}::jsonb)
    `,
  ]);
  return { id, status: "open" };
}

export type OpenSurveyRun = {
  id: string;
  surveyId: string;
  code: string;
  title: string;
  audience: string;
  openedAt: string;
  questions: Array<{ key: string; text: string; scale: number }>;
};

/**
 * The open survey runs and the questions they ask, for the person about to answer one.
 *
 * `answerSurvey` needs a `runId` and the question keys, and neither was reachable from a
 * self-service session: `GET /api/v1/surveys` is gated on `employee.write`, and survey runs
 * had no listing at all. This is that read and nothing else — `employee.read`, open runs
 * only, questions only. No response rows and no respondent identities are touched, so it
 * cannot weaken the anonymity `surveyResults` enforces.
 */
export async function listOpenSurveyRuns(access: Access): Promise<OpenSurveyRun[]> {
  enforce(access.context, "employee.read", { tenantId: access.tenantId });
  const [rows] = await tenantTx(access, [
    sqlClient`
      select r.id, r.created_at, r.attributes->>'audience' as audience,
             s.id as survey_id, s.attributes->>'code' as code, s.attributes->>'title' as title,
             s.attributes->'questions' as questions
      from survey_runs r
      join surveys s on s.id = r.survey_id and s.tenant_id = r.tenant_id
      where r.tenant_id = ${access.tenantId}
        and coalesce(r.attributes->>'status', 'open') = 'open'
      order by r.created_at desc
      limit 50
    `,
  ]);
  return (rows as Array<{
    id: string;
    created_at: string | Date;
    audience: string | null;
    survey_id: string;
    code: string | null;
    title: string | null;
    questions: unknown;
  }>).map((row) => ({
    id: row.id,
    surveyId: row.survey_id,
    code: row.code ?? "",
    title: row.title ?? "Untitled survey",
    audience: row.audience ?? "all",
    openedAt: row.created_at instanceof Date ? row.created_at.toISOString() : String(row.created_at),
    // A run whose survey carries no usable questions is returned with none, so the
    // caller shows an honest "nothing to answer" rather than an invented question.
    questions: (Array.isArray(row.questions) ? row.questions : []).flatMap((entry) => {
      const question = typeof entry === "object" && entry !== null ? (entry as Record<string, unknown>) : null;
      if (!question) return [];
      const key = typeof question.key === "string" ? question.key : "";
      const text = typeof question.text === "string" ? question.text : "";
      if (!key || !text) return [];
      const scale = Number(question.scale);
      return [{ key, text, scale: Number.isFinite(scale) && scale >= 2 && scale <= 10 ? Math.trunc(scale) : 5 }];
    }),
  }));
}

export const answerSurveySchema = z.object({
  runId: z.string().uuid(),
  answers: z.record(z.string(), z.number().int().min(1).max(10)).refine((value) => Object.keys(value).length > 0, "At least one answer is required."),
  anonymous: z.boolean().default(true),
});

export async function answerSurvey(access: Access, input: z.infer<typeof answerSurveySchema>) {
  enforce(access.context, "employee.read", { tenantId: access.tenantId });
  const [memberRows] = await tenantTx(access, [
    sqlClient`select employee_id from memberships where tenant_id = ${access.tenantId} and user_id = ${access.context.actorUserId} and status = 'active' limit 1`,
  ]);
  const employeeId = (memberRows as Array<{ employee_id: string | null }>)[0]?.employee_id ?? null;
  const id = crypto.randomUUID();
  await tenantTx(access, [
    sqlClient`
      insert into survey_responses (id, tenant_id, employee_id, survey_run_id, attributes)
      values (${id}, ${access.tenantId}, ${input.anonymous ? null : employeeId}, ${input.runId},
        ${JSON.stringify({ answers: input.answers, anonymous: input.anonymous })}::jsonb)
    `,
  ]);
  return { id };
}

export async function surveyResults(access: Access, runId: string) {
  enforce(access.context, "employee.read", { tenantId: access.tenantId });
  const [rows] = await tenantTx(access, [
    sqlClient`select attributes from survey_responses where tenant_id = ${access.tenantId} and survey_run_id = ${runId}`,
  ]);
  const responses = rows as Array<{ attributes: { answers: Record<string, number> } }>;
  if (responses.length < MIN_ANONYMITY_COHORT) {
    return { runId, suppressed: true, respondents: responses.length, threshold: MIN_ANONYMITY_COHORT, means: null };
  }
  const sums: Record<string, number> = {};
  const counts: Record<string, number> = {};
  for (const response of responses) {
    for (const [key, value] of Object.entries(response.attributes.answers)) {
      sums[key] = (sums[key] ?? 0) + value;
      counts[key] = (counts[key] ?? 0) + 1;
    }
  }
  const means: Record<string, number> = {};
  for (const key of Object.keys(sums)) means[key] = Math.round((sums[key]! / counts[key]!) * 100) / 100;
  return { runId, suppressed: false, respondents: responses.length, threshold: MIN_ANONYMITY_COHORT, means };
}
