import { NextResponse } from "next/server";

/**
 * GET /api/v1 — stable resource manifest for the upcoming frontend.
 * Lists every v1 family, its routes and auth model so new pages can be
 * built (and rearranged) without reading server sources. Versioned: any
 * breaking change ships as /api/v2 alongside, never by editing these.
 */
export const dynamic = "force-dynamic";

const RESOURCES = [
  { family: "platform-admin", routes: ["GET /api/v1/platform/tenants", "POST /api/v1/platform/tenants", "PATCH /api/v1/platform/tenants/:tenantId", "GET /api/v1/platform/tenants/:tenantId/users", "POST /api/v1/platform/tenants/:tenantId/users"], auth: "session + PLATFORM_ADMIN_EMAILS server allowlist. Creates client workspaces, owners and role-based users; status operations are audited and archive rather than purge data." },
  { family: "identity", routes: ["GET /api/v1/identity/context", "POST /api/v1/identity/context", "GET /api/v1/identity/memberships", "GET /api/v1/auth/registration-state", "GET /api/v1/workspace/bootstrap", "GET /api/v1/home", "GET /api/v1/search"], auth: "session", notes: "Tenant scope via mkraft_active_tenant cookie. Bootstrap and home are permission-filtered UI projections." },
  { family: "admin", routes: ["POST /api/v1/roles", "POST /api/v1/roles/:id/permissions", "POST /api/v1/memberships/roles", "POST /api/v1/invitations", "POST /api/v1/invitations/:id/revoke", "GET /api/v1/tenant/settings", "PATCH /api/v1/tenant/settings"], auth: "session + role.manage / membership.manage / tenant.manage / tenant.read. Invite tokens returned once, stored hashed." },
  { family: "people", routes: ["GET /api/v1/people", "GET /api/v1/people/:id", "POST /api/v1/people", "POST /api/v1/people/import-preview", "POST /api/v1/people/import-apply"], auth: "session + employee.read (compensation masked without payroll.rate.read); writes need employee.write; import apply needs employee.write" },
  { family: "attendance-ops", routes: ["POST /api/v1/regularizations", "POST /api/v1/regularizations/:id/decide", "POST /api/v1/shift-swaps", "POST /api/v1/shift-swaps/:id/decide", "GET /api/v1/exports", "POST /api/v1/exports", "GET /api/v1/exports/:id", "POST /api/v1/exports/:id/build"], auth: "session + attendance.write/read; exports honor the underlying resource permission" },
  { family: "reviews", routes: ["POST /api/v1/review-participants", "GET /api/v1/review-responses", "POST /api/v1/review-responses", "GET /api/v1/employee-skills", "POST /api/v1/skill-evidence", "POST /api/v1/skill-evidence/:id/verify"], auth: "session + employee.write/read; self reviews require subject login" },
  { family: "onboarding-admin", routes: ["GET /api/v1/onboarding/templates", "POST /api/v1/onboarding/templates", "PATCH /api/v1/onboarding/templates/:id"], auth: "session + employee.write/read" },
  { family: "organization", routes: ["GET /api/v1/organization/tree", "POST /api/v1/organization/departments", "POST /api/v1/organization/positions"], auth: "session + employee.read; writes need employee.write" },
  { family: "documents", routes: ["POST /api/v1/documents", "GET /api/v1/documents/:id/download", "POST /api/v1/documents/:id/scan"], auth: "session + employee.write (upload/scan), employee.read (download)" },
  { family: "attendance", routes: ["POST /api/v1/attendance/punches", "GET /api/v1/attendance/days", "GET /api/v1/attendance/team-summary", "GET /api/v1/attendance/days/:id/trace", "POST /api/v1/attendance/days/:id/recompute", "POST /api/v1/attendance/days/:id/transition"], auth: "session + attendance.write/read. Tenant owners and HR/time-office roles see the tenant; other users are restricted to their recursive reporting hierarchy. Trace is read-only; recompute is the explicit audited write." },
  { family: "gate-passes", routes: ["POST /api/v1/gate-passes", "POST /api/v1/gate-passes/:id/decide"], auth: "session + attendance.write" },
  { family: "leave", routes: ["GET /api/v1/leave-requests", "POST /api/v1/leave-requests", "POST /api/v1/leave-requests/:id/decide", "POST /api/v1/leave-requests/:id/early-return", "GET /api/v1/leave-balances", "POST /api/v1/coff-grants"], auth: "session + leave.read / leave.approve" },
  { family: "payroll", routes: ["GET /api/v1/payroll-runs", "POST /api/v1/payroll-runs", "GET /api/v1/payroll-runs/:id", "POST /api/v1/payroll-runs/:id/calculate", "POST /api/v1/payroll-runs/:id/approve", "POST /api/v1/payroll-runs/:id/finalize", "POST /api/v1/payroll-runs/:id/correct", "GET /api/v1/payroll-runs/:id/journal", "GET /api/v1/payslips/:id", "GET /api/v1/payroll-anomalies", "POST /api/v1/payroll-anomalies/:id/resolve", "POST /api/v1/wage-simulations"], auth: "session + payroll.run / payroll.read" },
  { family: "delegations", routes: ["GET /api/v1/delegations", "POST /api/v1/delegations", "POST /api/v1/delegations/:id/revoke"], auth: "session + membership.manage/read. Proxy self-approval is forbidden in leave decisions." },
  { family: "loans", routes: ["GET /api/v1/loans", "POST /api/v1/loans", "GET /api/v1/loans/:id", "POST /api/v1/loans/:id/consent", "POST /api/v1/loans/:id/approve", "POST /api/v1/loans/:id/disburse", "POST /api/v1/loans/:id/repay"], auth: "session + payroll.run / payroll.read" },
  { family: "salary-advances", routes: ["GET /api/v1/salary-advances", "POST /api/v1/salary-advances", "GET /api/v1/salary-advances/:id", "POST /api/v1/salary-advances/:id/approve", "POST /api/v1/salary-advances/:id/pay"], auth: "session + payroll.run / payroll.read. Blocked by open loans or advances; capped at one month basic." },
  { family: "payroll-inputs", routes: ["GET /api/v1/payroll-inputs", "POST /api/v1/payroll-inputs"], auth: "session + payroll.run / payroll.read. TDS, bonus, arrears and advance legs flow into calculation." },
  { family: "talent", routes: ["POST /api/v1/requisitions", "POST /api/v1/requisitions/:id/approve", "POST /api/v1/job-descriptions", "POST /api/v1/job-descriptions/:id/approve", "POST /api/v1/candidates", "POST /api/v1/candidates/:id/resume", "GET /api/v1/applications", "POST /api/v1/applications", "GET /api/v1/applications/:id", "POST /api/v1/applications/:id/score", "POST /api/v1/applications/:id/dispose", "POST /api/v1/applications/:id/advance", "POST /api/v1/offers", "POST /api/v1/offers/:id/transition", "POST /api/v1/interview-plans", "POST /api/v1/interview-sessions", "GET /api/v1/interview-sessions/:id/scores", "POST /api/v1/interview-scores", "POST /api/v1/interview-sessions/:id/debrief", "GET /api/v1/job-postings", "POST /api/v1/job-postings", "POST /api/v1/benefits/plans", "POST /api/v1/benefits/options", "GET /api/v1/benefits/enrollments", "POST /api/v1/benefits/enrollments", "POST /api/v1/benefits/claims"], auth: "session + employee.write/read. Score: one integer 0-100 only; disposition human-only; interview cards sealed until debrief." },
  { family: "onboarding", routes: ["GET /api/v1/onboarding/instances", "POST /api/v1/onboarding/instances", "GET /api/v1/onboarding/instances/:id/readiness", "POST /api/v1/onboarding/tasks/:id/complete"], auth: "session + employee.write/read" },
  { family: "offboarding", routes: ["POST /api/v1/offboarding/cases", "POST /api/v1/offboarding/items/:id/clear", "POST /api/v1/offboarding/cases/:id/settle"], auth: "session + employee.write; settle needs payroll.run" },
  { family: "performance", routes: ["POST /api/v1/review-cycles", "POST /api/v1/objectives", "POST /api/v1/key-results", "POST /api/v1/checkins", "GET /api/v1/feedback", "POST /api/v1/feedback", "POST /api/v1/feedback/entries", "POST /api/v1/calibration-sessions", "POST /api/v1/calibration-sessions/:id/adjust", "POST /api/v1/succession-plans"], auth: "session + employee.write/read. Feedback anonymized below 5 respondents." },
  { family: "learning", routes: ["GET /api/v1/courses", "POST /api/v1/courses", "POST /api/v1/learning-paths", "GET /api/v1/enrollments", "POST /api/v1/enrollments", "POST /api/v1/enrollments/:id/complete"], auth: "session + employee.write/read" },
  { family: "compensation", routes: ["POST /api/v1/compensation/bands", "POST /api/v1/compensation/cycles", "POST /api/v1/compensation/budgets", "GET /api/v1/compensation/proposals", "POST /api/v1/compensation/proposals", "POST /api/v1/compensation/proposals/:id/approve"], auth: "session + employee.write/read; approval needs payroll.run with maker/checker split" },
  { family: "engagement", routes: ["GET /api/v1/announcements", "POST /api/v1/announcements", "POST /api/v1/recognition-events", "POST /api/v1/referrals", "POST /api/v1/referrals/:id/award", "POST /api/v1/surveys", "POST /api/v1/survey-runs", "POST /api/v1/survey-responses", "GET /api/v1/survey-runs/:id/results"], auth: "session + employee.write/read. Pulse aggregate-only below threshold." },
  { family: "compliance", routes: ["GET /api/v1/compliance/obligations", "POST /api/v1/compliance/obligations", "GET /api/v1/compliance/forms", "POST /api/v1/compliance/evidence"], auth: "session + employee.write/read. Unvalidated packs stay unavailable (RULE_PACK_NOT_APPROVED)." },
  { family: "analytics", routes: ["GET /api/v1/analytics/metrics", "POST /api/v1/analytics/metrics", "POST /api/v1/analytics/metric-snapshots", "POST /api/v1/analytics/capability-index", "GET /api/v1/analytics/capability-index/:id"], auth: "session + employee.write/read" },
  { family: "contractors", routes: ["POST /api/v1/contractors/agencies", "POST /api/v1/contractors/contracts", "GET /api/v1/contractors/invoices", "POST /api/v1/contractors/invoices", "POST /api/v1/contractors/assignments"], auth: "session + employee.write/read. Variance over threshold holds invoices." },
  { family: "privacy", routes: ["POST /api/v1/privacy/requests", "POST /api/v1/privacy/requests/:id/close", "POST /api/v1/privacy/holds", "POST /api/v1/privacy/holds/:id/release"], auth: "session + employee.write. Erasure blocked under legal hold." },
  { family: "integrations", routes: ["GET /api/v1/integrations/catalog", "GET /api/v1/integrations/connections", "POST /api/v1/integrations/connections"], auth: "session + tenant.manage (mutate), employee.read (list). Secrets by reference only." },
  { family: "webhooks", routes: ["POST /api/v1/webhooks/endpoints", "POST /api/v1/webhooks/subscriptions", "GET /api/v1/webhooks/deliveries", "POST /api/v1/webhooks/deliveries/:id/replay", "POST /api/v1/webhooks/secrets", "POST /api/v1/webhooks/inbound/:connectionId", "GET /api/v1/webhooks/inbound"], auth: "session + tenant.manage / employee.read; inbound intake is public via HMAC + nonce" },
  { family: "ai", routes: ["GET /api/v1/ai/knowledge", "POST /api/v1/ai/knowledge", "POST /api/v1/ai/runs", "GET /api/v1/ai/runs/:id", "POST /api/v1/ai/feedback", "POST /api/v1/ai/reviews", "POST /api/v1/ai/reviews/:id/decide", "POST /api/v1/ai/actions", "GET /api/v1/ai/actions/:id", "POST /api/v1/ai/actions/:id/approve", "POST /api/v1/ai/actions/:id/execute", "POST /api/v1/ai/actions/:id/reverse", "POST /api/v1/ai/evals", "GET /api/v1/ai/evals/:id"], auth: "session + employee.write/read; action approval needs membership.manage; proposer != approver" },
  { family: "vp-readiness", routes: ["GET /api/v1/vp/readiness", "POST /api/v1/vp/readiness", "GET /api/v1/reports/team-history"], auth: "session + employee.read; commands require their underlying employee.write, attendance.write, leave.approve, payroll.run or tenant.manage permission. Consequential commands require Idempotency-Key." },
  { family: "ops", routes: ["GET /api/v1/ops/audit-events", "GET /api/v1/ops/access-events", "GET /api/v1/ops/outbox", "POST /api/v1/ops/outbox/:id/retry", "GET /api/v1/ops/scheduled-tasks", "POST /api/v1/ops/scheduled-tasks", "POST /api/v1/ops/scheduled-tasks/:id/cancel"], auth: "session + audit.read / tenant.read / tenant.manage" },
  { family: "notifications", routes: ["GET /api/v1/notifications", "POST /api/v1/notifications/preferences", "POST /api/v1/notifications/:id/read"], auth: "session; inbox is membership-scoped, mutes honored at fan-out" },
  { family: "fx", routes: ["GET /api/v1/fx/rates", "POST /api/v1/fx/rates"], auth: "session + employee.write/read. INR reporting with versioned FX snapshots." },
];

export async function GET() {
  return NextResponse.json(
    {
      version: "1",
      stability: "Breaking changes ship as /api/v2; v1 request/response shapes are frozen per route.",
      conventions: "Envelopes {data,meta,links}/{error}; cursor pagination max 100; Idempotency-Key on consequential POSTs; If-Match on irreversible transitions; money as decimal strings; tenant from session, never body.",
      resources: RESOURCES,
    },
    { headers: { "cache-control": "no-store" } },
  );
}
