// Generated by npm run data:manifest. JSON imports remain server-side.
import "server-only";
import workbook from "./workbook.json";
import resource0 from "./ui/components.AppWorkspace.json";
import resource1 from "./ui/components.Charts.NucleusChart.json";
import resource2 from "./ui/components.Charts.theme.json";
import resource3 from "./ui/components.Clerio.AIPanel.json";
import resource4 from "./ui/components.Clerio.AccessControlView.json";
import resource5 from "./ui/components.Clerio.ActionFormModal.json";
import resource6 from "./ui/components.Clerio.AdminOverview.json";
import resource7 from "./ui/components.Clerio.AttendanceFAB.json";
import resource8 from "./ui/components.Clerio.AttendanceView.json";
import resource9 from "./ui/components.Clerio.CMSModal.json";
import resource10 from "./ui/components.Clerio.CatalogGridView.json";
import resource11 from "./ui/components.Clerio.ChatPanel.json";
import resource12 from "./ui/components.Clerio.CompensationView.json";
import resource13 from "./ui/components.Clerio.ComplianceView.json";
import resource14 from "./ui/components.Clerio.ContractWorkforceView.json";
import resource15 from "./ui/components.Clerio.DataImportModal.json";
import resource16 from "./ui/components.Clerio.ExperienceView.json";
import resource17 from "./ui/components.Clerio.HelpdeskView.json";
import resource18 from "./ui/components.Clerio.IntegrationsView.json";
import resource19 from "./ui/components.Clerio.LearningView.json";
import resource20 from "./ui/components.Clerio.LeaveView.json";
import resource21 from "./ui/components.Clerio.LeftDock.json";
import resource22 from "./ui/components.Clerio.LoginView.json";
import resource23 from "./ui/components.Clerio.MainWorkspace.json";
import resource24 from "./ui/components.Clerio.MisReportingHub.json";
import resource25 from "./ui/components.Clerio.OnboardingView.json";
import resource26 from "./ui/components.Clerio.OperationalModuleView.json";
import resource27 from "./ui/components.Clerio.PayrollView.json";
import resource28 from "./ui/components.Clerio.PeopleCoreView.json";
import resource29 from "./ui/components.Clerio.PerformanceView.json";
import resource30 from "./ui/components.Clerio.ProjectView.json";
import resource31 from "./ui/components.Clerio.RecruitmentView.json";
import resource32 from "./ui/components.Clerio.RightSubNav.json";
import resource33 from "./ui/components.Clerio.SettingsView.json";
import resource34 from "./ui/components.Clerio.SideNav.json";
import resource35 from "./ui/components.Clerio.TeamView.json";
import resource36 from "./ui/components.Clerio.Toast.json";
import resource37 from "./ui/components.Clerio.TopNav.json";
import resource38 from "./ui/components.Clerio.WorkflowBuilderModal.json";
import resource39 from "./ui/components.Dashboard.AttendanceWidget.json";
import resource40 from "./ui/components.Dashboard.Header.json";
import resource41 from "./ui/components.Dashboard.HeroSection.json";
import resource42 from "./ui/components.Dashboard.Modals.AccessControlModal.json";
import resource43 from "./ui/components.Dashboard.Modals.ApprovalActionModal.json";
import resource44 from "./ui/components.Dashboard.StatsCards.json";
import resource45 from "./ui/components.Dashboard.TodaysFocus.json";
import resource46 from "./ui/components.Dashboard.UpcomingEvents.json";
import resource47 from "./ui/components.Dashboard.Views.AttendanceIntelligence.json";
import resource48 from "./ui/components.Dashboard.Views.EmployeeHome.json";
import resource49 from "./ui/components.Dashboard.Views.HROpsConsole.json";
import resource50 from "./ui/components.Dashboard.Views.MagnetixCapability.json";
import resource51 from "./ui/components.Dashboard.Views.ManagerCockpit.json";
import resource52 from "./ui/components.Dashboard.Views.NucleusIntelligence.json";
import resource53 from "./ui/components.Dashboard.Views.PayrollControlRoom.json";
import resource54 from "./ui/components.Dashboard.Views.PeopleCommandCentre.json";
import resource55 from "./ui/components.Dashboard.Views.PerformanceTalent.json";
import resource56 from "./ui/components.Dashboard.Views.TalentAcquisition.json";
import resource57 from "./ui/components.Navigation.DualPaneNav.json";
import resource58 from "./ui/components.auth.RoleProtected.json";
import resource59 from "./ui/context.AuthContext.json";
import resource60 from "./ui/context.HRMSContext.json";
import resource61 from "./ui/dashboard.widgets.json";
import resource62 from "./ui/leave.workflow.json";
import resource63 from "./ui/lib.demo-workbook-adapter.json";
import resource64 from "./ui/lib.mis-reporting.json";
import resource65 from "./ui/lib.navigation-access.json";
import resource66 from "./ui/lib.operational-module-registry.json";
import resource67 from "./ui/navigation.catalog.json";
import resource68 from "./ui/picklists.catalog.json";
import resource69 from "./ui/process.requirements.json";
import resource70 from "./ui/services.erpAndComplianceService.json";
import resource71 from "./ui/services.establishmentService.json";
import resource72 from "./ui/services.leaveEngine.json";
import resource73 from "./ui/services.payrollAdjacenciesService.json";
import resource74 from "./ui/services.timeOfficeEngine.json";
import resource75 from "./ui/services.workCalendarService.json";

export const workspaceResources = {
    workbook,
    "components.AppWorkspace": resource0,
    "components.Charts.NucleusChart": resource1,
    "components.Charts.theme": resource2,
    "components.Clerio.AIPanel": resource3,
    "components.Clerio.AccessControlView": resource4,
    "components.Clerio.ActionFormModal": resource5,
    "components.Clerio.AdminOverview": resource6,
    "components.Clerio.AttendanceFAB": resource7,
    "components.Clerio.AttendanceView": resource8,
    "components.Clerio.CMSModal": resource9,
    "components.Clerio.CatalogGridView": resource10,
    "components.Clerio.ChatPanel": resource11,
    "components.Clerio.CompensationView": resource12,
    "components.Clerio.ComplianceView": resource13,
    "components.Clerio.ContractWorkforceView": resource14,
    "components.Clerio.DataImportModal": resource15,
    "components.Clerio.ExperienceView": resource16,
    "components.Clerio.HelpdeskView": resource17,
    "components.Clerio.IntegrationsView": resource18,
    "components.Clerio.LearningView": resource19,
    "components.Clerio.LeaveView": resource20,
    "components.Clerio.LeftDock": resource21,
    "components.Clerio.LoginView": resource22,
    "components.Clerio.MainWorkspace": resource23,
    "components.Clerio.MisReportingHub": resource24,
    "components.Clerio.OnboardingView": resource25,
    "components.Clerio.OperationalModuleView": resource26,
    "components.Clerio.PayrollView": resource27,
    "components.Clerio.PeopleCoreView": resource28,
    "components.Clerio.PerformanceView": resource29,
    "components.Clerio.ProjectView": resource30,
    "components.Clerio.RecruitmentView": resource31,
    "components.Clerio.RightSubNav": resource32,
    "components.Clerio.SettingsView": resource33,
    "components.Clerio.SideNav": resource34,
    "components.Clerio.TeamView": resource35,
    "components.Clerio.Toast": resource36,
    "components.Clerio.TopNav": resource37,
    "components.Clerio.WorkflowBuilderModal": resource38,
    "components.Dashboard.AttendanceWidget": resource39,
    "components.Dashboard.Header": resource40,
    "components.Dashboard.HeroSection": resource41,
    "components.Dashboard.Modals.AccessControlModal": resource42,
    "components.Dashboard.Modals.ApprovalActionModal": resource43,
    "components.Dashboard.StatsCards": resource44,
    "components.Dashboard.TodaysFocus": resource45,
    "components.Dashboard.UpcomingEvents": resource46,
    "components.Dashboard.Views.AttendanceIntelligence": resource47,
    "components.Dashboard.Views.EmployeeHome": resource48,
    "components.Dashboard.Views.HROpsConsole": resource49,
    "components.Dashboard.Views.MagnetixCapability": resource50,
    "components.Dashboard.Views.ManagerCockpit": resource51,
    "components.Dashboard.Views.NucleusIntelligence": resource52,
    "components.Dashboard.Views.PayrollControlRoom": resource53,
    "components.Dashboard.Views.PeopleCommandCentre": resource54,
    "components.Dashboard.Views.PerformanceTalent": resource55,
    "components.Dashboard.Views.TalentAcquisition": resource56,
    "components.Navigation.DualPaneNav": resource57,
    "components.auth.RoleProtected": resource58,
    "context.AuthContext": resource59,
    "context.HRMSContext": resource60,
    "dashboard.widgets": resource61,
    "leave.workflow": resource62,
    "lib.demo-workbook-adapter": resource63,
    "lib.mis-reporting": resource64,
    "lib.navigation-access": resource65,
    "lib.operational-module-registry": resource66,
    "navigation.catalog": resource67,
    "picklists.catalog": resource68,
    "process.requirements": resource69,
    "services.erpAndComplianceService": resource70,
    "services.establishmentService": resource71,
    "services.leaveEngine": resource72,
    "services.payrollAdjacenciesService": resource73,
    "services.timeOfficeEngine": resource74,
    "services.workCalendarService": resource75,
};
